/**
 * Block Editor Default Code
 * Project: HC-05 Bluetooth Control (bluetooth-hc05)
 * Level: INTERMEDIATE | Category: Wireless Communication
 */

export const bluetoothHc05Block = {
  slug: "bluetooth-hc05",
  title: "HC-05 Bluetooth Control",
  level: "INTERMEDIATE",
  category: "Wireless Communication",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"forever\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"led_turn\"><field name=\"PIN\">13</field><field name=\"STATE\">ON</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"led_turn\"><field name=\"PIN\">13</field><field name=\"STATE\">OFF</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nvoid setup() {\n  pinMode(13, OUTPUT);\n}\n\nvoid loop() {\n  digitalWrite(13, HIGH);\n  delay(1000);\n  digitalWrite(13, LOW);\n  delay(1000);\n}\n\n",
};

export default bluetoothHc05Block;
