/**
 * Block Editor Default Code
 * Project: Control LED with Push Button (button-led)
 * Level: BEGINNER | Category: Basic Input + Control
 */

export const buttonLedBlock = {
  slug: "button-led",
  title: "Control LED with Push Button",
  level: "BEGINNER",
  category: "Basic Input + Control",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"on_start\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"button_setup\"><field name=\"PIN\">2</field><field name=\"PULL\">DOWN</field></block></statement></block><block type=\"forever\" x=\"20\" y=\"240\"><statement name=\"DO\"><block type=\"if_then_else\"><value name=\"COND\"><block type=\"button_is_pressed\"><field name=\"PIN\">2</field></block></value><statement name=\"DO\"><block type=\"led_turn\"><field name=\"PIN\">13</field><field name=\"STATE\">ON</field></block></statement><statement name=\"ELSE\"><block type=\"led_turn\"><field name=\"PIN\">13</field><field name=\"STATE\">OFF</field></block></statement><next><block type=\"wait_secs\"><field name=\"VAL\">0.1</field><field name=\"UNIT\">SEC</field></block></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nvoid setup() {\n  pinMode(2, INPUT);\n  pinMode(13, OUTPUT);\n}\n\nvoid loop() {\n  if (digitalRead(2) == HIGH) {\n    digitalWrite(13, HIGH);\n  } else {\n    digitalWrite(13, LOW);\n  }\n  delay(100);\n}\n\n",
};

export default buttonLedBlock;
