/**
 * Block Editor Default Code
 * Project: Turn ON Buzzer (buzzer)
 * Level: BEGINNER | Category: Basic Output
 */

export const buzzerBlock = {
  slug: "buzzer",
  title: "Turn ON Buzzer",
  level: "BEGINNER",
  category: "Basic Output",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"forever\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"buzzer_tone\"><field name=\"PIN\">8</field><value name=\"FREQ\"><block type=\"math_number\"><field name=\"NUM\">1000</field></block></value><value name=\"DUR\"><block type=\"math_number\"><field name=\"NUM\">1000</field></block></value><next><block type=\"buzzer_stop\"><field name=\"PIN\">8</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nvoid setup() {\n  pinMode(8, OUTPUT);\n}\n\nvoid loop() {\n  tone(8, 1000, 1000);\n  delay(1000);\n  noTone(8);\n  delay(1000);\n}\n\n",
};

export default buzzerBlock;
