/**
 * Block Editor Default Code
 * Project: DHT22 Sensor on LCD (dht-lcd)
 * Level: INTERMEDIATE | Category: Display System
 */

export const dhtLcdBlock = {
  slug: "dht-lcd",
  title: "DHT22 Sensor on LCD",
  level: "INTERMEDIATE",
  category: "Display System",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"on_start\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"temp_sensor_setup\"><field name=\"PIN\">6</field><next><block type=\"lcd_setup\"><field name=\"COLS\">16</field><field name=\"ROWS\">2</field><field name=\"ADDR\">0x27</field><next><block type=\"lcd_print\"><field name=\"TEXT\">DHT22 LCD Ready</field><field name=\"ROW\">0</field><field name=\"COL\">0</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></block></next></statement></block><block type=\"forever\" x=\"20\" y=\"240\"><statement name=\"DO\"><block type=\"lcd_clear\"><next><block type=\"lcd_print\"><field name=\"TEXT\">Temp (C):</field><field name=\"ROW\">0</field><field name=\"COL\">0</field><next><block type=\"lcd_print\"><field name=\"TEXT\">Humidity: %</field><field name=\"ROW\">1</field><field name=\"COL\">0</field><next><block type=\"wait_secs\"><field name=\"VAL\">2</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\n#include <Wire.h>\n#include <LiquidCrystal_I2C.h>\n#include <DHT.h>\nLiquidCrystal_I2C lcd(0x27, 16, 2);\nDHT dht(6, DHT11);\n\nvoid setup() {\n  dht.begin();\n  lcd.init();\n  lcd.backlight();\n  lcd.setCursor(0, 0);\n  lcd.print(\"DHT22 LCD Ready\");\n  delay(1000);\n}\n\nvoid loop() {\n  lcd.clear();\n  lcd.setCursor(0, 0);\n  lcd.print(\"Temp (C):\");\n  lcd.setCursor(0, 1);\n  lcd.print(\"Humidity: %\");\n  delay(2000);\n}\n\n",
};

export default dhtLcdBlock;
