/**
 * Block Editor Default Code
 * Project: Blink of LED (led-blink)
 * Level: BEGINNER | Category: Basic Output
 */

export const ledBlinkBlock = {
  slug: "led-blink",
  title: "Blink of LED",
  level: "BEGINNER",
  category: "Basic Output",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"forever\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"led_turn\"><field name=\"PIN\">13</field><field name=\"STATE\">ON</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"led_turn\"><field name=\"PIN\">13</field><field name=\"STATE\">OFF</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nvoid setup() {\n  pinMode(13, OUTPUT);\n}\n\nvoid loop() {\n  digitalWrite(13, HIGH);\n  delay(1000);\n  digitalWrite(13, LOW);\n  delay(1000);\n}\n\n",
};

export default ledBlinkBlock;
