/**
 * Block Editor Default Code
 * Project: LED Brightness Control using PWM (led-pwm)
 * Level: BEGINNER | Category: Basic Input + Control
 */

export const ledPwmBlock = {
  slug: "led-pwm",
  title: "LED Brightness Control using PWM",
  level: "BEGINNER",
  category: "Basic Input + Control",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><variables><variable type=\"Number\" id=\"var_i\">i</variable></variables><block type=\"forever\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"loop_with_for\"><field name=\"VAR\">i</field><field name=\"BY\">5</field><value name=\"FROM\"><block type=\"math_number\"><field name=\"NUM\">0</field></block></value><value name=\"TO\"><block type=\"math_number\"><field name=\"NUM\">255</field></block></value><statement name=\"DO\"><block type=\"led_fade\"><field name=\"PIN\">9</field><value name=\"BRIGHTNESS\"><block type=\"variables_get_number\"><field name=\"VAR\">i</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">0.01</field><field name=\"UNIT\">SEC</field></block></block></next></statement><next><block type=\"loop_with_for\"><field name=\"VAR\">i</field><field name=\"BY\">-5</field><value name=\"FROM\"><block type=\"math_number\"><field name=\"NUM\">255</field></block></value><value name=\"TO\"><block type=\"math_number\"><field name=\"NUM\">0</field></block></value><statement name=\"DO\"><block type=\"led_fade\"><field name=\"PIN\">9</field><value name=\"BRIGHTNESS\"><block type=\"variables_get_number\"><field name=\"VAR\">i</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">0.01</field><field name=\"UNIT\">SEC</field></block></block></next></statement></block></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nint i = 0;\n\nvoid setup() {\n  pinMode(9, OUTPUT);\n}\n\nvoid loop() {\n  for (int i=0; i<=255; i+=5) {\n    analogWrite(9, i);\n    delay(10);\n  }\n  for (int i=255; i>=0; i-=5) {\n    analogWrite(9, i);\n    delay(10);\n  }\n}\n\n",
};

export default ledPwmBlock;
