/**
 * Block Editor Default Code
 * Project: Potentiometer Controlled LED Brightness (potentiometer-led)
 * Level: BEGINNER | Category: Basic Analog Sensors
 */

export const potentiometerLedBlock = {
  slug: "potentiometer-led",
  title: "Potentiometer Controlled LED Brightness",
  level: "BEGINNER",
  category: "Basic Analog Sensors",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><variables><variable type=\"Number\" id=\"var_val\">val</variable></variables><block type=\"on_start\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"analog_sensor_setup\"><field name=\"PIN\">A0</field><field name=\"LABEL\">pot</field></block></statement></block><block type=\"forever\" x=\"20\" y=\"240\"><statement name=\"DO\"><block type=\"variables_set_number\"><field name=\"VAR\">val</field><value name=\"VALUE\"><block type=\"map_value\"><field name=\"FL\">0</field><field name=\"FH\">1023</field><field name=\"TL\">0</field><field name=\"TH\">255</field><value name=\"VAL\"><block type=\"analog_sensor_read\"><field name=\"PIN\">A0</field></block></value></block></value><next><block type=\"led_fade\"><field name=\"PIN\">3</field><value name=\"BRIGHTNESS\"><block type=\"variables_get_number\"><field name=\"VAR\">val</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">0.05</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nint val = 0;\n\nvoid setup() {\n  pinMode(A0, INPUT);\n  pinMode(3, OUTPUT);\n}\n\nvoid loop() {\n  val = map(analogRead(A0), 0, 1023, 0, 255);\n  analogWrite(3, val);\n  delay(50);\n}\n\n",
};

export default potentiometerLedBlock;
