/**
 * Block Editor Default Code
 * Project: Servo Motor Rotation (servo-motor)
 * Level: INTERMEDIATE | Category: Actuators and Motor Control
 */

export const servoMotorBlock = {
  slug: "servo-motor",
  title: "Servo Motor Rotation",
  level: "INTERMEDIATE",
  category: "Actuators and Motor Control",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"forever\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"rotate_servo\"><field name=\"PIN\">6</field><value name=\"DEG\"><block type=\"math_number\"><field name=\"NUM\">0</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"rotate_servo\"><field name=\"PIN\">6</field><value name=\"DEG\"><block type=\"math_number\"><field name=\"NUM\">90</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"rotate_servo\"><field name=\"PIN\">6</field><value name=\"DEG\"><block type=\"math_number\"><field name=\"NUM\">180</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></block></next></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\n#include <Servo.h>\nServo myServo_6;\n\nvoid setup() {\n  myServo_6.attach(6);\n}\n\nvoid loop() {\n  myServo_6.write(0);\n  delay(1000);\n  myServo_6.write(90);\n  delay(1000);\n  myServo_6.write(180);\n  delay(1000);\n}\n\n",
};

export default servoMotorBlock;
