/**
 * Block Editor Default Code
 * Project: Smart Dustbin (Ultrasonic + Servo) (smart-dustbin)
 * Level: INTERMEDIATE | Category: Smart Systems
 */

export const smartDustbinBlock = {
  slug: "smart-dustbin",
  title: "Smart Dustbin (Ultrasonic + Servo)",
  level: "INTERMEDIATE",
  category: "Smart Systems",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"on_start\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"rotate_servo\"><field name=\"PIN\">6</field><value name=\"DEG\"><block type=\"math_number\"><field name=\"NUM\">0</field></block></value></block></statement></block><block type=\"forever\" x=\"20\" y=\"240\"><statement name=\"DO\"><block type=\"digital_write_pin\"><field name=\"PIN\">9</field><field name=\"STATE\">LOW</field><next><block type=\"wait_secs\"><field name=\"VAL\">0.002</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">9</field><field name=\"STATE\">HIGH</field><next><block type=\"wait_secs\"><field name=\"VAL\">0.01</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">9</field><field name=\"STATE\">LOW</field><next><block type=\"rotate_servo\"><field name=\"PIN\">6</field><value name=\"DEG\"><block type=\"math_number\"><field name=\"NUM\">90</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">2</field><field name=\"UNIT\">SEC</field><next><block type=\"rotate_servo\"><field name=\"PIN\">6</field><value name=\"DEG\"><block type=\"math_number\"><field name=\"NUM\">0</field></block></value><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\n#include <Servo.h>\nServo myServo_6;\n\nvoid setup() {\n  pinMode(9, OUTPUT);\n  myServo_6.attach(6);\n  myServo_6.write(0);\n}\n\nvoid loop() {\n  digitalWrite(9, LOW);\n  delay(2);\n  digitalWrite(9, HIGH);\n  delay(10);\n  digitalWrite(9, LOW);\n  myServo_6.write(90);\n  delay(2000);\n  myServo_6.write(0);\n  delay(1000);\n}\n\n",
};

export default smartDustbinBlock;
