/**
 * Block Editor Default Code
 * Project: Temperature Sensor (NTC) with Buzzer Alarm (temperature-sensor)
 * Level: BEGINNER | Category: Basic Analog Sensors
 */

export const temperatureSensorBlock = {
  slug: "temperature-sensor",
  title: "Temperature Sensor (NTC) with Buzzer Alarm",
  level: "BEGINNER",
  category: "Basic Analog Sensors",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"on_start\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"thermistor_setup\"><field name=\"PIN\">A0</field></block></statement></block><block type=\"forever\" x=\"20\" y=\"240\"><statement name=\"DO\"><block type=\"if_then_else\"><value name=\"COND\"><block type=\"math_compare\"><field name=\"OP\">GTE</field><value name=\"A\"><block type=\"thermistor_read\"><field name=\"UNIT\">C</field><field name=\"PIN\">A0</field></block></value><value name=\"B\"><block type=\"math_number\"><field name=\"NUM\">30</field></block></value></block></value><statement name=\"DO\"><block type=\"buzzer_tone\"><field name=\"PIN\">8</field><value name=\"FREQ\"><block type=\"math_number\"><field name=\"NUM\">900</field></block></value><value name=\"DUR\"><block type=\"math_number\"><field name=\"NUM\">200</field></block></value></block></statement><statement name=\"ELSE\"><block type=\"buzzer_stop\"><field name=\"PIN\">8</field></block></statement><next><block type=\"wait_secs\"><field name=\"VAL\">0.2</field><field name=\"UNIT\">SEC</field></block></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nvoid setup() {\n  pinMode(A0, INPUT);\n  pinMode(8, OUTPUT);\n}\n\nvoid loop() {\n  if (((analogRead(A0) * 0.48828125) >= 30)) {\n    tone(8, 900, 200);\n    delay(200);\n  } else {\n    noTone(8);\n  }\n  delay(200);\n}\n\n",
};

export default temperatureSensorBlock;
