/**
 * Block Editor Default Code
 * Project: Traffic Light System (traffic-light)
 * Level: BEGINNER | Category: Basic Output
 */

export const trafficLightBlock = {
  slug: "traffic-light",
  title: "Traffic Light System",
  level: "BEGINNER",
  category: "Basic Output",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"forever\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"digital_write_pin\"><field name=\"PIN\">11</field><field name=\"STATE\">HIGH</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">10</field><field name=\"STATE\">LOW</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">9</field><field name=\"STATE\">LOW</field><next><block type=\"wait_secs\"><field name=\"VAL\">5</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">11</field><field name=\"STATE\">LOW</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">10</field><field name=\"STATE\">HIGH</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">9</field><field name=\"STATE\">LOW</field><next><block type=\"wait_secs\"><field name=\"VAL\">2</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">11</field><field name=\"STATE\">LOW</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">10</field><field name=\"STATE\">LOW</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">9</field><field name=\"STATE\">HIGH</field><next><block type=\"wait_secs\"><field name=\"VAL\">5</field><field name=\"UNIT\">SEC</field></block></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nvoid setup() {\n  pinMode(11, OUTPUT);\n  pinMode(10, OUTPUT);\n  pinMode(9, OUTPUT);\n}\n\nvoid loop() {\n  digitalWrite(11, HIGH);\n  digitalWrite(10, LOW);\n  digitalWrite(9, LOW);\n  delay(5000);\n  digitalWrite(11, LOW);\n  digitalWrite(10, HIGH);\n  digitalWrite(9, LOW);\n  delay(2000);\n  digitalWrite(11, LOW);\n  digitalWrite(10, LOW);\n  digitalWrite(9, HIGH);\n  delay(5000);\n}\n\n",
};

export default trafficLightBlock;
