/**
 * Block Editor Default Code
 * Project: Up Counter (up-counter)
 * Level: BEGINNER | Category: Basic Counters
 */

export const upCounterBlock = {
  slug: "up-counter",
  title: "Up Counter",
  level: "BEGINNER",
  category: "Basic Counters",
  useBlocklyCode: true,
  blocklyXml: "<xml xmlns=\"https://developers.google.com/blockly/xml\"><variables><variable type=\"Number\" id=\"var_count\">count</variable></variables><block type=\"forever\" x=\"20\" y=\"20\"><statement name=\"DO\"><block type=\"digital_write_pin\"><field name=\"PIN\">10</field><field name=\"STATE\">HIGH</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">10</field><field name=\"STATE\">LOW</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">11</field><field name=\"STATE\">HIGH</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">11</field><field name=\"STATE\">LOW</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">12</field><field name=\"STATE\">HIGH</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">12</field><field name=\"STATE\">LOW</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">13</field><field name=\"STATE\">HIGH</field><next><block type=\"wait_secs\"><field name=\"VAL\">1</field><field name=\"UNIT\">SEC</field><next><block type=\"digital_write_pin\"><field name=\"PIN\">13</field><field name=\"STATE\">LOW</field></block></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></statement></block></xml>",
  blocklyGeneratedCode: "// Generated by OpenHW Studio Block Editor\n\nint count = 0;\n\nvoid setup() {\n  pinMode(10, OUTPUT);\n  pinMode(11, OUTPUT);\n  pinMode(12, OUTPUT);\n  pinMode(13, OUTPUT);\n}\n\nvoid loop() {\n  digitalWrite(10, HIGH);\n  delay(1000);\n  digitalWrite(10, LOW);\n  digitalWrite(11, HIGH);\n  delay(1000);\n  digitalWrite(11, LOW);\n  digitalWrite(12, HIGH);\n  delay(1000);\n  digitalWrite(12, LOW);\n  digitalWrite(13, HIGH);\n  delay(1000);\n  digitalWrite(13, LOW);\n}\n\n",
};

export default upCounterBlock;
