import { test, expect } from '@playwright/test';

const LED_CODE = `// Generated by OpenHW Studio Block Editor

void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  digitalWrite(13, HIGH);
  delay(1000);
  digitalWrite(13, LOW);
  delay(1000);
}
`;

function buildLedProject(overrides: Partial<Record<string, unknown>> = {}) {
  const withResistor = overrides.withResistor !== false;
  const components = [
    {
      id: 'uno1',
      type: 'openhw-arduino-uno',
      label: 'Arduino Uno',
      x: 120,
      y: 160,
      w: 311,
      h: 228,
      rotation: 0,
      attrs: {},
    },
    ...(withResistor
      ? [{
          id: 'r1',
          type: 'openhw-resistor',
          label: 'Resistor 220 ohm',
          x: 480,
          y: 160,
          w: 60,
          h: 12,
          rotation: 0,
          attrs: { value: '220' },
        }]
      : []),
    {
      id: 'led1',
      type: 'openhw-led',
      label: 'LED',
      x: 570,
      y: 150,
      w: 40,
      h: 40,
      rotation: 0,
      attrs: { color: 'red' },
    },
  ];

  const connections = withResistor
    ? [
        { id: 'w_1', from: 'uno1:13', to: 'r1:p1', color: 'red', waypoints: [] },
        { id: 'w_2', from: 'r1:p2', to: 'led1:A', color: 'red', waypoints: [] },
        { id: 'w_3', from: 'led1:K', to: 'uno1:gnd_1', color: 'black', waypoints: [] },
      ]
    : [
        { id: 'w_1', from: 'uno1:13', to: 'led1:A', color: 'red', waypoints: [] },
        { id: 'w_2', from: 'led1:K', to: 'uno1:gnd_1', color: 'black', waypoints: [] },
      ];

  const now = Date.now();
  return {
    id: String(overrides.id || `electrosim-final-${withResistor ? 'good' : 'bad'}`),
    name: String(overrides.name || (withResistor ? 'ElectroSim Final LED' : 'ElectroSim Broken LED')),
    owner: 'guest',
    board: 'openhw-arduino-uno',
    components,
    connections,
    wires: connections,
    code: LED_CODE,
    blocklyXml: '',
    blocklyGeneratedCode: LED_CODE,
    useBlocklyCode: true,
    projectFiles: [],
    openCodeTabs: [],
    activeCodeFileId: 'code.ino',
    version: 1,
    savedAt: now,
    ...overrides,
  };
}

async function seedProject(page, project: ReturnType<typeof buildLedProject>) {
  await page.goto('/maintenance.html', { waitUntil: 'domcontentloaded' });
  await page.evaluate(async (seed) => {
    window.localStorage.setItem('openhw-tour-completed', 'true');
    window.localStorage.setItem('ohw_autosave_enabled', 'false');
    window.sessionStorage.setItem('ohw_session_active', '1');

    await new Promise<void>((resolve, reject) => {
      const del = window.indexedDB.deleteDatabase('openhw-projects');
      del.onsuccess = () => resolve();
      del.onerror = () => reject(del.error);
      del.onblocked = () => resolve();
    });

    await new Promise<void>((resolve, reject) => {
      const req = window.indexedDB.open('openhw-projects', 3);
      req.onupgradeneeded = (event) => {
        const db = (event.target as IDBOpenDBRequest).result;
        if (!db.objectStoreNames.contains('projects')) {
          const store = db.createObjectStore('projects', { keyPath: 'id' });
          store.createIndex('by_owner_ts', ['owner', 'savedAt'], { unique: false });
        }
        if (!db.objectStoreNames.contains('pendingCloudQueue')) {
          db.createObjectStore('pendingCloudQueue', { keyPath: 'projectId' });
        }
        if (!db.objectStoreNames.contains('pendingDeleteQueue')) {
          db.createObjectStore('pendingDeleteQueue', { keyPath: 'projectId' });
        }
      };
      req.onerror = () => reject(req.error);
      req.onsuccess = () => {
        const db = req.result;
        const tx = db.transaction('projects', 'readwrite');
        tx.objectStore('projects').put(seed);
        tx.oncomplete = () => {
          db.close();
          resolve();
        };
        tx.onerror = () => {
          db.close();
          reject(tx.error);
        };
      };
    });
  }, project);
}

async function openSeededSimulator(page) {
  await page.goto('/simulator', { waitUntil: 'domcontentloaded' });
  await page.locator('#comp-master-uno1').waitFor({ state: 'attached', timeout: 60000 });
  await page.locator('#comp-master-led1').waitFor({ state: 'attached', timeout: 60000 });
  await expect(page.locator('main').getByText('Arduino Uno', { exact: true }).last()).toBeVisible({ timeout: 60000 });
  await expect(page.locator('main').getByText('LED', { exact: true }).last()).toBeVisible({ timeout: 60000 });
  await expect(page.getByRole('region', { name: 'AI electronics tutor' })).toBeVisible();
}

async function selectComponent(page, componentId: string) {
  await page.evaluate((id) => {
    const host = document.querySelector(`#comp-master-${id}`);
    const hit = host?.querySelector(`#comp-hit-${id} div[style*="cursor: move"]`) || host?.querySelector(`#comp-hit-${id}`);
    if (!hit) throw new Error(`Component hit target not found: ${id}`);
    hit.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, clientX: 200, clientY: 200 }));
  }, componentId);
}

async function runAiButton(page, label: string, expected: RegExp | string) {
  const panel = page.getByRole('region', { name: 'AI electronics tutor' });
  await panel.getByRole('button', { name: label }).click();
  await expect(panel.getByText(expected).last()).toBeVisible({ timeout: 10000 });
}

test.describe('ElectroSim AI final integration smoke', () => {
  test.setTimeout(180000);

  test('validates good and wrong LED circuits through simulator, validation, AI tutor, challenges, score, signal flow, and save/load', async ({ page }) => {
    await seedProject(page, buildLedProject());
    await openSeededSimulator(page);

    await selectComponent(page, 'led1');
    await expect(page.getByText(/LED selected/i)).toBeVisible({ timeout: 10000 });

    await runAiButton(page, 'Part', /LED \(led1\)/);
    await runAiButton(page, 'Explain', /This circuit contains 3 components and 3 wires/);
    await runAiButton(page, 'Debug', /No rule-based validation problems detected/);
    await runAiButton(page, 'Connect', /Connection guidance for LED/);

    await runAiButton(page, 'Hint', /Hint 1:/);
    await runAiButton(page, 'Hint', /Hint 2:/);
    await runAiButton(page, 'Hint', /Hint 3:/);

    const panel = page.getByRole('region', { name: 'AI electronics tutor' });
    await panel.getByRole('button', { name: 'Check' }).click();
    await expect(panel.getByText(/LED Control complete/)).toBeVisible({ timeout: 10000 });
    await expect(panel.getByText(/Skill Score:/)).toBeVisible();
    await panel.getByTitle('Show signal flow').click();
    await expect(panel.getByText(/Visual signal flow:/)).toBeVisible({ timeout: 10000 });

    await page.getByTitle('Run').click();
    await expect(page.getByRole('button', { name: /Compiling|Booting|Running|Stop/ }).first()).toBeVisible({ timeout: 60000 });
    const stop = page.getByTitle('Stop');
    if (await stop.isVisible().catch(() => false)) {
      await stop.click();
    }

    await page.getByRole('button', { name: 'File', exact: true }).click();
    await page.locator('text=Save').first().click();
    await page.locator('input[placeholder="Project name..."]').fill('ElectroSim Final Saved LED');
    await page.getByRole('button', { name: 'Save' }).last().click();
    await expect(page.locator('input[placeholder="Project name..."]')).toHaveCount(0, { timeout: 10000 });

    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('#comp-master-r1').waitFor({ state: 'attached', timeout: 60000 });
    await page.locator('#wire-path-ui-w_2').waitFor({ state: 'attached', timeout: 60000 });
    await expect(page.locator('main').getByText('Resistor 220 ohm', { exact: true }).last()).toBeVisible({ timeout: 60000 });

    await seedProject(page, buildLedProject({ withResistor: false }));
    await openSeededSimulator(page);
    await selectComponent(page, 'led1');

    await runAiButton(page, 'Debug', /current-limiting resistor/);
    await panel.getByRole('button', { name: 'Check' }).click();
    await expect(panel.getByText(/not complete yet/)).toBeVisible({ timeout: 10000 });
    await expect(panel.getByText(/Add a current-limiting resistor/)).toBeVisible();

    await runAiButton(page, 'Hint', /Hint 1:/);
    await runAiButton(page, 'Hint', /Hint 2:/);
    await runAiButton(page, 'Hint', /Hint 3:/);
    await runAiButton(page, 'Explain', /This circuit contains 2 components and 2 wires/);
    await runAiButton(page, 'Connect', /Connection guidance for LED/);
  });
});
