import { useState, useEffect, useRef, useCallback } from "react";
import { useParams, useNavigate, useLocation } from "react-router-dom";
import { useAuth } from "../../context/AuthContext.jsx";
import { getResolvedClassAdventure } from "../../services/classAdventureService";
import { updateClassAdventureConfig } from "../../services/classAdventureService";
import { getProjectFlashcards } from "../../services/gamification/ProjectData";
import { PROJECTS } from "../../services/gamification/ProjectsConfig";
import { COMPONENTS, CATEGORIES } from "../../services/gamification/ComponentsConfig";
import { extractProjectMetaFromPng } from "../../utils/projectCompilerUtils";
import { createProjectBankEntry, getMyProjectBank, getProjectBySlug, updateProjectBankEntry, publishProjectBankEntry, unpublishProjectBankEntry } from "../../services/projectBankService";
import ProjectBankModal from "../../components/teacher/class-detail/ProjectBankModal.jsx";

const getEntityId = (value) => {
  if (!value) return "";
  if (typeof value === "string") return value;
  return value._id || value.id || value.toString?.() || "";
};

const DIFFICULTY_OPTIONS = [
  { value: "easy", label: "Easy" },
  { value: "intermediate", label: "Intermediate" },
  { value: "hard", label: "Hard" },
];

const DIFFICULTY_ORDER = {
  easy: 0,
  intermediate: 1,
  hard: 2,
};

const normalizeDifficulty = (value, fallback = "intermediate") => {
  const raw = String(value || "").trim().toLowerCase();
  if (raw === "beginner") return "easy";
  if (raw === "advanced") return "hard";
  if (raw === "easy" || raw === "intermediate" || raw === "hard") return raw;
  return fallback;
};

const difficultyLabel = (value) => {
  const normalized = normalizeDifficulty(value);
  return normalized.charAt(0).toUpperCase() + normalized.slice(1);
};

const filterAndSortByDifficulty = (items, filterValue, sortValue) => {
  const indexed = (items || []).map((item, index) => ({ item, index }));
  const filtered = indexed.filter(({ item }) => {
    if (!filterValue || filterValue === "all") return true;
    return normalizeDifficulty(item?.difficulty) === filterValue;
  });

  if (sortValue === "difficulty-asc") {
    return [...filtered].sort((a, b) => {
      const diff = DIFFICULTY_ORDER[normalizeDifficulty(a.item?.difficulty)] - DIFFICULTY_ORDER[normalizeDifficulty(b.item?.difficulty)];
      if (diff !== 0) return diff;
      return String(a.item?.front || a.item?.question || "").localeCompare(String(b.item?.front || b.item?.question || ""));
    });
  }

  if (sortValue === "difficulty-desc") {
    return [...filtered].sort((a, b) => {
      const diff = DIFFICULTY_ORDER[normalizeDifficulty(b.item?.difficulty)] - DIFFICULTY_ORDER[normalizeDifficulty(a.item?.difficulty)];
      if (diff !== 0) return diff;
      return String(a.item?.front || a.item?.question || "").localeCompare(String(b.item?.front || b.item?.question || ""));
    });
  }

  return filtered;
};

const normalizeTheoryCard = (card, fallbackDifficulty = "intermediate") => ({
  ...card,
  difficulty: normalizeDifficulty(card?.difficulty, fallbackDifficulty),
});

const normalizeQuizQuestion = (question, fallbackDifficulty = "intermediate") => ({
  ...question,
  difficulty: normalizeDifficulty(question?.difficulty, fallbackDifficulty),
});

const SIMULATOR_CRITERIA_STORAGE_KEY = "bankProjectCriteria";

const createDefaultAssessment = () => ({
  passingThreshold: 60,
  refCircuitFile: null,
  refCircuitName: "",
  evaluationCriteria: null,
  autoGeneratedStatus: null,
  autoGeneratedError: "",
  overrideJson: "",
});

export default function TeacherProjectContentEditor() {
  const { classId, projectSlug } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const { user } = useAuth();

  const query = new URLSearchParams(location.search);
  const bankMode = location.pathname.includes("/project-bank/");
  const isNewBankProject = location.pathname.includes("/project-bank/new");
  const initialBankVisibility = query.get("visibility") || "personal";
  const [bankVisibility, setBankVisibility] = useState(initialBankVisibility);
  const [bankProjectId, setBankProjectId] = useState(null);
  const [bankProjectOwnerId, setBankProjectOwnerId] = useState("");
  const [bankLoading, setBankLoading] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [bankModalOpen, setBankModalOpen] = useState(false);
  const [bankProjects, setBankProjects] = useState([]);
  const [customTitle, setCustomTitle] = useState("");
  const importedFromSimulatorRef = useRef(false);

  const [theoryCards, setTheoryCards] = useState([]);
  const [quizQuestions, setQuizQuestions] = useState([]);
  const [projectDifficulty, setProjectDifficulty] = useState("intermediate");
  const [theoryDifficultyFilter, setTheoryDifficultyFilter] = useState("all");
  const [theoryDifficultySort, setTheoryDifficultySort] = useState("original");
  const [quizDifficultyFilter, setQuizDifficultyFilter] = useState("all");
  const [quizDifficultySort, setQuizDifficultySort] = useState("original");
  const [rewardComponents, setRewardComponents] = useState([]);
  const [rewardSearchQuery, setRewardSearchQuery] = useState("");
  const [rewardCategoryFilter, setRewardCategoryFilter] = useState("All");
  const [assessmentNodeContent, setAssessmentNodeContent] = useState({
    passingThreshold: 60,
    refCircuitFile: null,
    refCircuitName: "",
    evaluationCriteria: null,
    autoGeneratedStatus: null, // null | "ok" | "error"
    autoGeneratedError: "",
    overrideJson: "",
  });

  const [activeTab, setActiveTab] = useState("theory");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [savingBank, setSavingBank] = useState(false);
  const [error, setError] = useState("");
  const [successMsg, setSuccessMsg] = useState("");
  const currentUserId = getEntityId(user);
  const canEditBankProject = isNewBankProject || !bankProjectOwnerId || bankProjectOwnerId === currentUserId;

  const rewardCategories = CATEGORIES || ["All", "Input", "Output", "Passive", "Sensor", "Actuator"];
  const filteredRewardComponents = COMPONENTS.filter((comp) => {
    const categoryMatches = rewardCategoryFilter === "All" || comp.category === rewardCategoryFilter;
    const query = rewardSearchQuery.trim().toLowerCase();
    const searchMatches =
      !query ||
      [comp.name, comp.fullName, comp.category, comp.description]
        .filter(Boolean)
        .some((value) => String(value).toLowerCase().includes(query));
    return categoryMatches && searchMatches;
  });

  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      setLoading(true);
      setError("");

      // Check if we're returning from simulator with criteria to import
      const params = new URLSearchParams(location.search);
      const returningFromSimulator = params.get("simulatorCriteria") === "1";
      const storedCriteria = localStorage.getItem(SIMULATOR_CRITERIA_STORAGE_KEY);
      const buildSimulatorImportedAssessment = (baseAssessment = createDefaultAssessment()) => {
        if (!returningFromSimulator || !storedCriteria) return null;
        try {
          const parsed = JSON.parse(storedCriteria);
          if (parsed && Array.isArray(parsed.components) && Array.isArray(parsed.connections)) {
            const meta = {
              components: parsed.components,
              connections: parsed.connections,
              code: parsed.code || "",
            };
            const criteria = buildEvaluationCriteriaFromMeta(meta);
            const scoring = buildDefaultScoring(criteria);
            const rewardIds = (criteria.components?.required || [])
              .map((req) => req.type)
              .filter((slug) => COMPONENTS.some((c) => c.id === slug));
            return {
              ...baseAssessment,
              evaluationCriteria: { ...criteria, ...(scoring ? { scoring } : {}) },
              autoGeneratedStatus: "ok",
              autoGeneratedError: "",
              refCircuitName: baseAssessment.refCircuitName || "Imported from simulator",
              _rewardIds: rewardIds,
            };
          }
        } catch (e) {
          console.error("Failed to process criteria from storage in load effect", e);
        }
        return null;
      };

      if (bankMode) {
        if (isNewBankProject) {
          importedFromSimulatorRef.current = false;
          const template = getProjectFlashcards(projectSlug);
          const defaultDifficulty = normalizeDifficulty(projectMeta?.difficulty || "intermediate");
          const newCards = template.map((card, idx) => ({
            id: `card-${Date.now()}-${idx}`,
            emoji: card.emoji || "📚",
            front: card.front || "",
            simple: card.simple || "",
            detail: card.detail || "",
            funFact: card.funFact || "",
            difficulty: normalizeDifficulty(card.difficulty, defaultDifficulty),
          }));
          if (!cancelled) {
            setProjectDifficulty(defaultDifficulty);
            setTheoryCards(newCards);
            setQuizQuestions(
              template.map((card, i) => ({
                id: `quiz-${Date.now()}-${i}`,
                question: card.quiz?.question || card.front || "",
                options: card.quiz?.options?.slice(0, 4) || ["", "", "", ""],
                correctAnswer: Number.isFinite(card.quiz?.correctAnswer)
                  ? card.quiz.correctAnswer
                  : 0,
                difficulty: normalizeDifficulty(card.quiz?.difficulty, defaultDifficulty),
              }))
            );
            setBankProjectId(null);
            setBankVisibility(initialBankVisibility);
            setCustomTitle(projectMeta?.title || projectSlug || "");
            const importedAssessment = buildSimulatorImportedAssessment(createDefaultAssessment());
            setAssessmentNodeContent(importedAssessment || createDefaultAssessment());
            if (importedAssessment?._rewardIds?.length) {
              setRewardComponents((prev) => [...new Set([...prev, ...importedAssessment._rewardIds])]);
            }
            setLoading(false);
          }
          return;
        }

        try {
          const data = await getProjectBySlug(projectSlug);
          const project = data?.project || data;
          if (cancelled) return;
          if (!project) {
            setError("Project not found in bank.");
            setBankProjectId(null);
            setBankProjectOwnerId("");
            setBankVisibility(initialBankVisibility);
            setCustomTitle("");
            return;
          }
          const defaultDifficulty = normalizeDifficulty(project.difficulty || projectMeta?.difficulty || "intermediate");
          setProjectDifficulty(defaultDifficulty);
          setTheoryCards((project.theory || []).map((card) => normalizeTheoryCard(card, defaultDifficulty)));
          setQuizQuestions((project.quizQuestions || []).map((question) => normalizeQuizQuestion(question, defaultDifficulty)));
          const rewardIds = (project.rewardComponents || []).map(c => c.id).filter(Boolean);
          setRewardComponents(rewardIds);
          const baseAssessment = project.assessment || createDefaultAssessment();
          const importedAssessment = buildSimulatorImportedAssessment(baseAssessment);
          setAssessmentNodeContent(importedAssessment || baseAssessment);
          if (importedAssessment?._rewardIds?.length) {
            setRewardComponents((prev) => [...new Set([...prev, ...importedAssessment._rewardIds])]);
          }
          setBankProjectOwnerId(getEntityId(project.owner));
          setBankVisibility(project.visibility || "personal");
          setCustomTitle(project.title || "");
        } catch (err) {
          if (!cancelled) setError(err?.message || "Failed to load bank project");
        } finally {
          importedFromSimulatorRef.current = false;
          if (!cancelled) setLoading(false);
        }
        return;
      }

      try {
        const response = await getResolvedClassAdventure(classId);
        if (cancelled) return;
        const project = response?.resolved?.projects?.find(
          (p) => p.slug === projectSlug
        );
        if (!project) {
          // Create new project from template
          const template = getProjectFlashcards(projectSlug);
          const defaultDifficulty = normalizeDifficulty(projectMeta?.difficulty || "intermediate");
          const newCards = template.map((card, idx) => ({
            id: `card-${Date.now()}-${idx}`,
            emoji: card.emoji || "📚",
            front: card.front || "",
            simple: card.simple || "",
            detail: card.detail || "",
            funFact: card.funFact || "",
            difficulty: normalizeDifficulty(card.difficulty, defaultDifficulty),
          }));
          setProjectDifficulty(defaultDifficulty);
          setTheoryCards(newCards);
          setQuizQuestions(
            template.map((card, i) => ({
              id: `quiz-${Date.now()}-${i}`,
              question: card.quiz?.question || card.front || "",
              options: card.quiz?.options?.slice(0, 4) || ["", "", "", ""],
              correctAnswer: Number.isFinite(card.quiz?.correctAnswer)
                ? card.quiz.correctAnswer
                : 0,
              difficulty: normalizeDifficulty(card.quiz?.difficulty, defaultDifficulty),
            }))
          );
          // New projects start with no reward components selected
          setRewardComponents([]);
          const importedAssessment = buildSimulatorImportedAssessment(createDefaultAssessment());
          setAssessmentNodeContent(importedAssessment || createDefaultAssessment());
          if (importedAssessment?._rewardIds?.length) {
            setRewardComponents((prev) => [...new Set([...prev, ...importedAssessment._rewardIds])]);
          }
        } else {
          const defaultDifficulty = normalizeDifficulty(project.difficulty || projectMeta?.difficulty || "intermediate");
          setProjectDifficulty(defaultDifficulty);
          setTheoryCards((project.theory || []).map((card) => normalizeTheoryCard(card, defaultDifficulty)));
          setQuizQuestions((project.quizQuestions || []).map((question) => normalizeQuizQuestion(question, defaultDifficulty)));
          // Extract component IDs from rewardComponents array
          const rewardIds = (project.rewardComponents || []).map(c => c.id).filter(Boolean);
          setRewardComponents(rewardIds);
          const baseAssessment = project.assessment || createDefaultAssessment();
          const importedAssessment2 = buildSimulatorImportedAssessment(baseAssessment);
          setAssessmentNodeContent(importedAssessment2 || baseAssessment);
          if (importedAssessment2?._rewardIds?.length) {
            setRewardComponents((prev) => [...new Set([...prev, ...importedAssessment2._rewardIds])]);
          }
        }
      } catch (err) {
        setError(err?.message || "Failed to load project content");
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();
    return () => {
      cancelled = true;
    };
  }, [classId, projectSlug, bankMode, isNewBankProject, initialBankVisibility]);

  const projectMeta = PROJECTS.find((p) => p.slug === projectSlug);
  const color = projectMeta?.color || "#3b82f6";
  const visibleTheoryCards = filterAndSortByDifficulty(
    theoryCards,
    theoryDifficultyFilter,
    theoryDifficultySort
  );
  const visibleQuizQuestions = filterAndSortByDifficulty(
    quizQuestions,
    quizDifficultyFilter,
    quizDifficultySort
  );

  // Theory card handlers
  const updateCard = (index, field, value) => {
    setTheoryCards((prev) =>
      prev.map((card, i) => (i === index ? { ...card, [field]: value } : card))
    );
  };

  const addCard = () => {
    setTheoryCards((prev) => [
      ...prev,
      {
        id: `card-${Date.now()}`,
        emoji: "📚",
        front: "",
        simple: "",
        detail: "",
        funFact: "",
        difficulty: projectDifficulty,
      },
    ]);
  };

  const removeCard = (index) => {
    setTheoryCards((prev) => prev.filter((_, i) => i !== index));
  };

  // Quiz handlers
  const updateQuizQuestion = (index, field, value) => {
    setQuizQuestions((prev) =>
      prev.map((q, i) => (i === index ? { ...q, [field]: value } : q))
    );
  };

  const updateQuizOption = (index, optIdx, value) => {
    setQuizQuestions((prev) =>
      prev.map((q, i) =>
        i === index
          ? {
            ...q,
            options: (q.options || ["", "", "", ""]).map((opt, j) =>
              j === optIdx ? value : opt
            ),
          }
          : q
      )
    );
  };

  const addQuizQuestion = () => {
    setQuizQuestions((prev) => [
      ...prev,
      {
        id: `quiz-${Date.now()}`,
        question: "",
        options: ["", "", "", ""],
        correctAnswer: 0,
        explanation: "",
        difficulty: projectDifficulty,
      },
    ]);
  };

  const removeQuizQuestion = (index) => {
    setQuizQuestions((prev) => prev.filter((_, i) => i !== index));
  };

  // Assessment node content handlers
  const updateAssessmentField = (field, value) => {
    setAssessmentNodeContent((prev) => ({ ...prev, [field]: value }));
  };

  // ── Ref. circuit PNG handlers ────────────────────────────────────────────
  const refCircuitInputRef = useRef(null);

  const handleRefCircuitUpload = useCallback(async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      const arrayBuffer = await file.arrayBuffer();
      const meta = extractProjectMetaFromPng(arrayBuffer);

      const criteria = buildEvaluationCriteriaFromMeta(meta);
      const scoring = buildDefaultScoring(criteria);
      const combined = { ...criteria, ...(scoring ? { scoring } : {}) };

      setAssessmentNodeContent(prev => ({
        ...prev,
        refCircuitFile: arrayBuffer,
        refCircuitName: file.name,
        evaluationCriteria: combined,
        autoGeneratedStatus: "ok",
        autoGeneratedError: "",
      }));

      const rewardIdsFromMeta = (combined.components?.required || [])
        .map((req) => req.type)
        .filter((slug) => COMPONENTS.some((c) => c.id === slug));

      if (rewardIdsFromMeta.length > 0) {
        setRewardComponents((prev) => [...new Set([...prev, ...rewardIdsFromMeta])]);
      }
    } catch (err) {
      setAssessmentNodeContent(prev => ({
        ...prev,
        refCircuitFile: null,
        refCircuitName: "",
        evaluationCriteria: null,
        autoGeneratedStatus: "error",
        autoGeneratedError: err.message || "Failed to extract circuit data from PNG.",
      }));
    }
  }, []);

  const handleClearRefCircuit = () => {
    setAssessmentNodeContent(prev => ({
      ...prev,
      refCircuitFile: null,
      refCircuitName: "",
      evaluationCriteria: null,
      autoGeneratedStatus: null,
      autoGeneratedError: "",
      overrideJson: "",
    }));
    if (refCircuitInputRef.current) refCircuitInputRef.current.value = "";
  };

  // ── Meta → evaluationCriteria builder ───────────────────────────────────
  const compTypeMap = {
    arduino: 'arduino',
    uno: 'arduino',
    led: 'led',
    rgbled: 'rgb-led',
    'rgb led': 'rgb-led',
    resistor: 'resistor',
    '220r': 'resistor',
    '220 ohm': 'resistor',
    'potentiometer': 'potentiometer',
    pot: 'potentiometer',
    'buzzer': 'buzzer',
    'analog joystick': 'analog-joystick',
    joystick: 'analog-joystick',
    ldr: 'ldr',
    photoresistor: 'ldr',
    button: 'button',
    pushbutton: 'button',
    switch: 'switch',
    dcmotor: 'dc-motor',
    servo: 'servo',
    'servo motor': 'servo',
    sensor: 'sensor',
    display: 'display',
  };

  // ── helpers shared by buildEvaluationCriteriaFromMeta ─────────────────
  // Maps raw Wokwi component type strings → canonical slugs used by evaluateAssessment
  const TYPE_RE = [
    { slug: 'arduino', re: /(?:openhw[-_])?arduino(?:[-_\s]uno)?|wokwi[-_]arduino[-_]uno|wokwi[-_]esp32[-_]uno/i },
    { slug: 'rgb-led', re: /(?:openhw[-_])?rgb[-_\s]?led|wokwi[-_]rgb[-_]led/i },
    { slug: 'resistor', re: /(?:openhw[-_])?resistor|wokwi[-_]resistor/i },
    { slug: 'dc-motor', re: /(?:openhw[-_])?dc[-_\s]?motor|wokwi[-_]dc[-_]motor/i },
    { slug: 'servo', re: /(?:openhw[-_])?servo|wokwi[-_]servo/i },
    { slug: 'potentiometer', re: /(?:openhw[-_])?potentiometer|wokwi[-_]potentiometer/i },
    { slug: 'analog-joystick', re: /(?:openhw[-_])?analog[-_]joystick|wokwi[-_]analog[-_]joystick/i },
    { slug: 'buzzer', re: /(?:openhw[-_])?buzzer|wokwi[-_]buzzer/i },
    { slug: 'ldr', re: /(?:openhw[-_])?ldr|photoresistor|photo[-_]resistor|wokwi[-_]ldr/i },
    { slug: 'button', re: /(?:openhw[-_])?button|pushbutton|wokwi[-_]button/i },
    { slug: 'switch', re: /(?:openhw[-_])?switch|wokwi[-_]switch/i },
    { slug: 'led', re: /(?:openhw[-_])?led(?:[-_])?|wokwi[-_]led/i },
  ];

  function typeFromRaw(rawType) {
    const t = String(rawType || "").toLowerCase();
    for (const { slug, re } of TYPE_RE) { if (re.test(t)) return slug; }
    // fallback: strip "openhw-" or "wokwi-" prefix, normalise separators
    const clean = t.replace(/^(?:openhw|wokwi)[-_]/, "").replace(/[-_]/g, " ");
    return compTypeMap[clean] || clean.replace(/\s+/g, "-") || t;
  }

  function resolveRoleSlug(slug) {
    const s = String(slug || "").toLowerCase().replace(/^(?:openhw|wokwi)[-_]/, "").replace(/[-_]/g, " ");
    return compTypeMap[s] || s || null;
  }

  function buildEvaluationCriteriaFromMeta(meta) {
    const comps = Array.isArray(meta.components) ? meta.components : [];
    const connections = Array.isArray(meta.connections) ? meta.connections : [];
    const code = String(meta.code || "").trim();

    // ─────────────────────────────────────────────────────────
    // 1. Map each component id → its type slug (used in both loops)
    // ─────────────────────────────────────────────────────────
    const typeMap = {};   // id → type-slug  e.g. "uno1" → "arduino"
    for (const c of comps) {
      const rawType = String(c.type || "");
      typeMap[String(c.id)] = typeFromRaw(rawType);
    }

    // ─────────────────────────────────────────────────────────
    // 2. Component counts  (only non-breadboard parts)
    // ─────────────────────────────────────────────────────────
    const typeCount = {};
    for (const c of comps) {
      const id = String(c.id);
      const slug = typeMap[id];
      if (!slug) continue;
      typeCount[slug] = (typeCount[slug] || 0) + 1;
    }
    const required = Object.entries(typeCount).map(([type, count]) => ({ type, count }));

    // ─────────────────────────────────────────────────────────
    // 3. Wires → requiredConnections  (matched against student
    //    submitted wires via evaluateAssessment / wm() matcher)
    // ─────────────────────────────────────────────────────────
    // meta.connections[].from/to are strings like "uno1:D13", "led1:A"
    // Map each unique endpoint → its role type + pin label
    const epRole = {};
    const epPin = {};
    const pinRole = {};   // pin → corresponding role label

    for (const w of connections) {
      const each = [w.from, w.to];
      for (const ep of each) {
        if (epRole[ep]) continue;
        const m = String(ep).match(/^([^:]+):(.+)$/);
        if (!m) continue;
        const compId = m[1], pinName = m[2];
        const roleSlug = resolveRoleSlug(typeMap[compId]) || typeMap[compId] || compId;
        epRole[ep] = roleSlug;
        epPin[ep] = pinName;
        pinRole[pinName] = roleSlug;
      }
    }

    // Derive `pinOf` lookup: pinName → { role, pairedRole, pairedPin }
    // This models the "wire endpoint" rules that evaluateAssessment checks
    const pinOf = {};
    for (const w of connections) {
      const [rFrom, rTo] = [w.from, w.to];
      const f = epRole[rFrom] ? { role: epRole[rFrom], pin: epPin[rFrom], id: rFrom.split(":")[0] } : null;
      const t = epRole[rTo] ? { role: epRole[rTo], pin: epPin[rTo], id: rTo.split(":")[0] } : null;
      if (f && t) {
        if (!pinOf[f.role]) pinOf[f.role] = {};
        pinOf[f.role][f.pin] = { pairedRole: t.role, pairedPin: t.pin };
      }
    }

    const requiredConnections = Object.entries(pinOf).flatMap(([role, pins]) =>
      Object.entries(pins).map(([pin, { pairedRole, pairedPin }]) => ({
        from: { component: String(role), pin: String(pin) },
        to: { component: String(pairedRole), pin: String(pairedPin) },
      }))
    );

    // ─────────────────────────────────────────────────────────
    // 4. Code → requiredFunctions + expectedBehavior
    // ─────────────────────────────────────────────────────────
    const allFunctions = code.match(/\b([a-zA-Z_]\w*)\s*\(/g) || [];
    const builtIns = new Set('if for while switch case return break continue else void int float double char bool long unsigned short static const sizeof pinMode digitalWrite analogWrite delay Serial begin print println digitalRead analogRead tone noTone'.split(' '));
    const fnSet = [...new Set(allFunctions.map(m => m.replace(/\($/, "").trim()).filter(n => /^[A-Za-z_]/.test(n) && n.length >= 2 && !builtIns.has(n)))];
    const requiredFunctions = fnSet.slice(0, 8);

    const expectedBehavior = {};
    const pm = code.match(/pinMode\s*\(\s*(\d+)\s*,\s*(\w+)\s*\)/i);
    if (pm) { expectedBehavior.pinNumber = Number(pm[1]); expectedBehavior.pinMode = pm[2].toUpperCase(); }
    const dly1 = code.match(/delay\s*\(\s*(\d+)\s*\)/i);
    if (dly1) expectedBehavior.blinkDelay = Number(dly1[1]);
    const dly2 = code.match(/digitalWrite\s*\(.*?,\s*HIGH\s*\)[\s\S]{0,80}delay\s*\(\s*(\d+)/i);
    if (!dly2) { const dly3 = code.match(/delay\s*\(\s*(\d+)\s*\)/i); if (dly3) expectedBehavior.blinkDelay = Number(dly3[1]); }

    return {
      wiringAccuracy: { requiredConnections, weight: 0.35 },
      components: { required, weight: 0.25 },
      codeFunctionality: { requiredFunctions, expectedBehavior, weight: 0.40 },
    };
  }

  function buildDefaultScoring(criteria) {
    if (!criteria) return null;
    const mkTier = (label, fb) => ({ [label]: { min: { excellent: 90, good: 75, needsImprovement: 0 }[label], feedback: fb } });
    return {
      components: {
        excellent: { min: 90, feedback: "All required components are present!" },
        good: { min: 75, feedback: "Most required components are present." },
        needsImprovement: { min: 0, feedback: "Missing one or more required components." },
      },
      wiringAccuracy: {
        excellent: { min: 90, feedback: "All connections are correct!" },
        good: { min: 75, feedback: "Most connections are correct with minor issues." },
        needsImprovement: { min: 0, feedback: "Wiring needs significant correction." },
      },
      ...(criteria.codeFunctionality ? {
        codeFunctionality: {
          excellent: { min: 90, feedback: "Code logic matches expected behavior perfectly!" },
          good: { min: 75, feedback: "Code works but may need minor improvements." },
          needsImprovement: { min: 0, feedback: "Code functionality needs significant work." },
        },
      } : {}),
    };
  }

  // Rewards/Components handlers
  const toggleComponent = (compId) => {
    setRewardComponents((prev) =>
      prev.includes(compId)
        ? prev.filter((id) => id !== compId)
        : [...prev, compId]
    );
  };

  const handleSave = async () => {
    // Validation - Theory
    for (let i = 0; i < theoryCards.length; i++) {
      const card = theoryCards[i];
      if (!card.front?.trim()) {
        setError(`Theory Card ${i + 1}: Front (question) is required.`);
        setActiveTab("theory");
        return;
      }
      if (!card.simple?.trim()) {
        setError(`Theory Card ${i + 1}: Simple summary is required.`);
        setActiveTab("theory");
        return;
      }
      if (!card.detail?.trim()) {
        setError(`Theory Card ${i + 1}: Detail explanation is required.`);
        setActiveTab("theory");
        return;
      }
    }

    // Validation - Quiz
    for (let i = 0; i < quizQuestions.length; i++) {
      const q = quizQuestions[i];
      if (!q.question?.trim()) {
        setError(`Quiz Question ${i + 1}: Question text is required.`);
        setActiveTab("quiz");
        return;
      }
      const nonEmptyOptions = (q.options || []).filter((opt) => opt?.trim());
      if (nonEmptyOptions.length < 2) {
        setError(`Quiz Question ${i + 1}: At least 2 options are required.`);
        setActiveTab("quiz");
        return;
      }
      if (q.correctAnswer < 0 || q.correctAnswer > 3) {
        setError(`Quiz Question ${i + 1}: Correct answer must be A, B, C, or D.`);
        setActiveTab("quiz");
        return;
      }
    }

    // Validation - Assessment
    const threshold = assessmentNodeContent.passingThreshold;
    if (threshold !== undefined && threshold !== "") {
      const numThreshold = Number(threshold);
      if (!Number.isInteger(numThreshold) || numThreshold < 0 || numThreshold > 100) {
        setError("Assessment: Passing threshold must be an integer from 0 to 100.");
        setActiveTab("assessment");
        return;
      }
    }

    setSaving(true);
    setError("");
    setSuccessMsg("");
    try {
      const response = await getResolvedClassAdventure(classId);
      const currentConfig = response?.resolved || { worlds: [], projects: [] };
      const activeDifficulty = normalizeDifficulty(projectDifficulty || projectMeta?.difficulty || "intermediate");
      const sanitizedTheoryCards = theoryCards.map((card) => normalizeTheoryCard(card, activeDifficulty));
      const sanitizedQuizQuestions = quizQuestions.map((question) => normalizeQuizQuestion(question, activeDifficulty));

      const existingIndex = currentConfig.projects.findIndex(
        (p) => p.slug === projectSlug
      );

      // Build rewardComponents array with full component data (using openhw-* format)
      const selectedRewardComponents = COMPONENTS.filter((c) =>
        rewardComponents.includes(c.id)
      ).map(({ id, name, icon, color, description }) => ({
        type: `openhw-${id}`,
        name,
        icon,
        color,
        desc: description || "",
      }));

      const makeAssessmentContent = () => {
        const thr = Number.isInteger(assessmentNodeContent.passingThreshold)
          ? assessmentNodeContent.passingThreshold
          : 60;
        const content = { passingThreshold: thr };
        if (assessmentNodeContent.evaluationCriteria) {
          content.evaluationCriteria = assessmentNodeContent.evaluationCriteria;
        }
        let override = {};
        try { override = JSON.parse(assessmentNodeContent.overrideJson || "{}"); }
        catch { override = {}; }
        if (Object.keys(override).length) content.manualOverride = override;
        return content;
      };

      let updatedProject;
      if (existingIndex >= 0) {
        const existing = currentConfig.projects[existingIndex];
        const sanitizedAssessmentContent = makeAssessmentContent();
        updatedProject = {
          ...existing,
          difficulty: activeDifficulty,
          theory: sanitizedTheoryCards,
          quizQuestions: sanitizedQuizQuestions,
          rewardComponents: selectedRewardComponents,
          assessment: sanitizedAssessmentContent,
        };
      } else {
        const sanitizedAssessmentContent = makeAssessmentContent();
        updatedProject = {
          id: `custom-${projectSlug}-${Date.now()}`,
          slug: projectSlug,
          worldId: `world-1`,
          order: (currentConfig.projects?.length || 0) + 1,
          enabled: true,
          title: projectMeta?.title || projectSlug,
          difficulty: activeDifficulty,
          prerequisite: null,
          xpReward: 100,
          rewardComponents: selectedRewardComponents,
          theory: sanitizedTheoryCards,
          quizQuestions: sanitizedQuizQuestions,
          assessment: sanitizedAssessmentContent,
        };
      }

      const mergedProjects = existingIndex >= 0
        ? currentConfig.projects.map((p, i) => (i === existingIndex ? updatedProject : p))
        : [...(currentConfig.projects || []), updatedProject];

      const newConfig = {
        ...currentConfig,
        projects: mergedProjects,
      };

      await updateClassAdventureConfig(classId, newConfig);
      setSuccessMsg("Project content saved successfully!");
      setTimeout(() => {
        navigate(`/teacher/classes/${classId}`);
      }, 1200);
    } catch (err) {
      setError(err?.message || "Failed to save project content");
    } finally {
      setSaving(false);
    }
  };

  const buildBankPayload = () => {
    const displayTitle = customTitle.trim() || projectMeta?.title || projectSlug || "";
    // For new bank projects (no projectSlug in URL), use the custom title as slug
    const resolvedSlug = isNewBankProject ? customTitle.trim() : projectSlug;
    const activeDifficulty = normalizeDifficulty(projectDifficulty || projectMeta?.difficulty || "intermediate");
    const sanitizedTheoryCards = theoryCards.map((card) => normalizeTheoryCard(card, activeDifficulty));
    const sanitizedQuizQuestions = quizQuestions.map((question) => normalizeQuizQuestion(question, activeDifficulty));
    return {
      title: displayTitle || "Untitled Project",
      slug: resolvedSlug || displayTitle,
      description: projectMeta?.description || "",
      difficulty: activeDifficulty,
      visibility: bankVisibility,
      components: PROJECTS.find((p) => p.slug === projectSlug)?.components || [],
      starterCode: PROJECTS.find((p) => p.slug === projectSlug)?.starterCode || "",
      theory: sanitizedTheoryCards,
      quizQuestions: sanitizedQuizQuestions,
      rewardComponents: rewardComponents.map((id) => {
        const comp = COMPONENTS.find((c) => c.id === id);
        return comp
          ? {
            id: comp.id,
            type: comp.id,
            name: comp.name,
            icon: comp.icon,
            color: comp.color,
            description: comp.description || "",
          }
          : { id };
      }),
      assessment: assessmentNodeContent.evaluationCriteria
        ? { ...assessmentNodeContent, evaluationCriteria: assessmentNodeContent.evaluationCriteria }
        : {},
    };
  };

  const handleSaveToBank = async () => {
    setSavingBank(true);
    setError("");
    try {
      const payload = buildBankPayload();
      let targetProjectId = bankProjectId;
      let resolvedExistingProject = null;

      // For NEW bank projects, slug must exist; for EDIT mode, projectSlug must exist
      if (!payload.slug) {
        throw new Error("Please enter a project name before saving.");
      }
      if (!isNewBankProject && !projectSlug) {
        throw new Error("Cannot save: project identifier is missing. Please navigate to this page from the Project Bank list.");
      }

      if (!targetProjectId && payload.slug) {
        try {
          const existingResult = await getProjectBySlug(payload.slug);
          resolvedExistingProject = existingResult?.project || existingResult || null;
          targetProjectId = resolvedExistingProject?._id || resolvedExistingProject?.id || null;
        } catch (lookupError) {
          resolvedExistingProject = null;
        }
      }

      if (!canEditBankProject && !isNewBankProject) {
        const copyPayload = {
          ...payload,
          slug: `${payload.slug || "project"}-copy-${Date.now()}`,
          title: `${payload.title || "Project"} (Copy)`,
          visibility: "personal",
        };
        const result = await createProjectBankEntry(copyPayload);
        const createdProject = result?.project || result;
        setBankProjectId(createdProject?._id || createdProject?.id || null);
        setBankProjectOwnerId(currentUserId);
        setBankVisibility(createdProject?.visibility || "personal");
        setCustomTitle(createdProject?.title || copyPayload.title);
        setSuccessMsg("Shared project copied to your bank.");
      } else if (targetProjectId) {
        const result = await updateProjectBankEntry(targetProjectId, payload);
        const updatedProject = result?.project || result;
        setBankProjectId(updatedProject?._id || updatedProject?.id || targetProjectId);
        setBankProjectOwnerId(getEntityId(updatedProject?.owner) || currentUserId);
        setBankVisibility(updatedProject?.visibility || payload.visibility || "personal");
        setCustomTitle(updatedProject?.title || payload.title);
        setSuccessMsg(resolvedExistingProject ? "Bank project updated." : "Project saved to bank.");
      } else if (isNewBankProject || !bankProjectId) {
        const result = await createProjectBankEntry(payload);
        const createdProject = result?.project || result;
        setBankProjectId(createdProject?._id || createdProject?.id || bankProjectId);
        setBankProjectOwnerId(currentUserId);
        setSuccessMsg("Project created in bank.");
      } else {
        const result = await updateProjectBankEntry(bankProjectId, payload);
        const updatedProject = result?.project || result;
        setBankProjectId(updatedProject?._id || updatedProject?.id || bankProjectId);
        setBankProjectOwnerId(getEntityId(updatedProject?.owner) || currentUserId);
        setBankVisibility(updatedProject?.visibility || payload.visibility || "personal");
        setCustomTitle(updatedProject?.title || payload.title);
        setSuccessMsg("Bank project updated.");
      }
      setTimeout(() => setSuccessMsg(""), 3000);
    } catch (e) {
      if (e?.response?.status === 409 && e?.response?.data?.message?.includes("slug")) {
        try {
          const payload = buildBankPayload();
          const existingResult = await getProjectBySlug(payload.slug);
          const existingProject = existingResult?.project || existingResult;
          const existingId = existingProject?._id || existingProject?.id;
          if (existingId) {
            const result = await updateProjectBankEntry(existingId, payload);
            const updatedProject = result?.project || result;
            setBankProjectId(updatedProject?._id || updatedProject?.id || existingId);
            setBankProjectOwnerId(getEntityId(updatedProject?.owner) || currentUserId);
            setBankVisibility(updatedProject?.visibility || payload.visibility || "personal");
            setCustomTitle(updatedProject?.title || payload.title);
            setSuccessMsg("Bank project updated.");
            setError("");
            setTimeout(() => setSuccessMsg(""), 3000);
            return;
          }
        } catch (retryError) {
          console.error("Failed to update existing bank project after slug conflict:", retryError);
        }
      }

      const message =
        e?.response?.data?.message ||
        e?.response?.data?.error ||
        e?.message ||
        "Failed to save to project bank";
      setError(message);
    } finally {
      setSavingBank(false);
    }
  };

  const handlePublishToggle = async () => {
    const next = bankVisibility === "published" ? "personal" : "published";
    setError("");
    if (isNewBankProject) {
      setBankVisibility(next);
      setSuccessMsg(next === "published" ? "Project will be published when saved." : "Project will remain personal when saved.");
      setTimeout(() => setSuccessMsg(""), 3000);
      return;
    }

    if (!bankProjectId) {
      setError("Cannot update visibility: project identifier is missing.");
      return;
    }
    if (!canEditBankProject) {
      setError("Save a copy to your bank before changing visibility.");
      return;
    }

    setPublishing(true);
    try {
      if (next === "published") {
        await publishProjectBankEntry(bankProjectId);
      } else {
        await unpublishProjectBankEntry(bankProjectId);
      }
      setBankVisibility(next);
      setSuccessMsg(next === "published" ? "Project published to shared bank." : "Project moved to personal.");
      setTimeout(() => setSuccessMsg(""), 3000);
    } catch (e) {
      setError(e?.message || "Failed to update visibility");
    } finally {
      setPublishing(false);
    }
  };

  useEffect(() => {
    const criteria = assessmentNodeContent.evaluationCriteria;
    const slugs = criteria
      ? (criteria.components?.required || [])
        .map((req) => req.type)
        .filter((slug) => COMPONENTS.some((c) => c.id === slug))
      : [];
    setRewardComponents([...new Set(slugs)]);
  }, [assessmentNodeContent.evaluationCriteria]);

  const handleReturnFromSimulator = useCallback(() => {
    // Just clean up localStorage - the loading effect already processed the criteria
    const stored = localStorage.getItem(SIMULATOR_CRITERIA_STORAGE_KEY);
    if (stored) {
      localStorage.removeItem(SIMULATOR_CRITERIA_STORAGE_KEY);
    }
  }, []);

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    if (params.get("simulatorCriteria") === "1") {
      setActiveTab("assessment");
      // Remove the URL param after processing
      params.delete("simulatorCriteria");
      const nextSearch = params.toString();
      navigate(`${location.pathname}${nextSearch ? `?${nextSearch}` : ""}`, { replace: true });
    }
  }, [location, navigate]);

  const handleLoadFromBank = async () => {
    setBankLoading(true);
    try {
      const data = await getMyProjectBank();
      setBankProjects(data?.projects || data || []);
      setBankModalOpen(true);
    } catch (e) {
      setError(e?.message || "Failed to load project bank");
    } finally {
      setBankLoading(false);
    }
  };

  const handleBankProjectSelect = (bankProject) => {
    const loadedDifficulty = normalizeDifficulty(bankProject?.difficulty || projectDifficulty || projectMeta?.difficulty || "intermediate");
    setProjectDifficulty(loadedDifficulty);
    if (bankProject.theory?.length) {
      setTheoryCards(bankProject.theory.map((card) => normalizeTheoryCard(card, loadedDifficulty)));
    }
    if (bankProject.quizQuestions?.length) {
      setQuizQuestions(bankProject.quizQuestions.map((question) => normalizeQuizQuestion(question, loadedDifficulty)));
    }
    if (bankProject.rewardComponents?.length) {
      setRewardComponents(bankProject.rewardComponents.map((c) => c.id || c.type || c));
    }
    if (bankProject.assessment) {
      setAssessmentNodeContent((prev) => ({
        ...prev,
        ...bankProject.assessment,
        autoGeneratedStatus: bankProject.assessment.evaluationCriteria ? "ok" : null,
      }));
    }
    setBankModalOpen(false);
    setSuccessMsg("Project loaded from bank.");
    setTimeout(() => setSuccessMsg(""), 3000);
  };

  if (loading) {
    return (
      <div style={{ padding: 40, textAlign: "center" }}>
        <p>Loading project content...</p>
      </div>
    );
  }

  return (
    <div className="teacher-editor-page">
      <header className="student-db-header">
        {/* Left: logo + back button */}
        <div className="student-db-header__left" style={{ gap: 16 }}>
          <a href="/" className="student-db-header__brand">
            <img src="/logo-cropped.png" alt="OpenHW Studio" style={{ height: '65px', width: '130px', objectFit: 'contain' }} />
          </a>
          <button
            type="button"
            onClick={() => bankMode ? navigate("/teacher/project-bank") : navigate(`/teacher/classes/${classId}`)}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              padding: '7px 14px', borderRadius: 8,
              border: '1px solid var(--border)', background: 'var(--bg3)',
              color: 'var(--text)', fontWeight: 700, fontSize: 13,
              cursor: 'pointer', fontFamily: 'inherit',
            }}
          >
            ← {bankMode ? 'Project Bank' : 'Back to Class'}
          </button>
        </div>

        {/* Center: project title + difficulty */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            {bankMode ? (
              <input
                type="text"
                value={customTitle || ''}
                onChange={(e) => setCustomTitle(e.target.value)}
                style={{
                  fontSize: 15, fontWeight: 800, color: 'var(--text)',
                  background: 'transparent', border: '1px solid var(--border)',
                  borderRadius: 8, padding: '5px 12px', width: 240,
                  fontFamily: 'inherit', outline: 'none', textAlign: 'center',
                }}
                placeholder="Project title..."
              />
            ) : (
              <span style={{ fontSize: 15, fontWeight: 800, color: 'var(--text)' }}>
                {projectMeta?.title || projectSlug}
              </span>
            )}

            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ fontSize: 11, fontWeight: 800, color: '#94a3b8' }}>DIFFICULTY:</span>
              <select
                value={projectDifficulty}
                onChange={(e) => setProjectDifficulty(normalizeDifficulty(e.target.value))}
                style={{
                  fontSize: 11, fontWeight: 800, color: 'var(--text2)',
                  background: 'var(--bg3)', border: '1px solid var(--border)',
                  borderRadius: 8, padding: '3px 8px', outline: 'none',
                  cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase'
                }}
              >
                {DIFFICULTY_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <span style={{ fontSize: 10, color: '#94a3b8', fontWeight: 800, letterSpacing: '0.1em', marginTop: 4 }}>CONTENT EDITOR</span>
        </div>

        {/* Right: visibility + actions */}
        <div className="student-db-header__right">
          {bankMode && (
            <label style={{ display: 'inline-flex', alignItems: 'center', gap: 7, fontSize: 12, fontWeight: 700, color: '#64748b', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={bankVisibility === 'published'}
                onChange={handlePublishToggle}
                disabled={publishing || savingBank || !canEditBankProject}
              />
              Publish
            </label>
          )}
          <button
            type="button"
            onClick={() => bankMode ? navigate('/teacher/project-bank') : navigate(`/teacher/classes/${classId}`)}
            disabled={saving || savingBank}
            style={{
              padding: '7px 14px', borderRadius: 8, border: '1px solid var(--border)',
              background: 'var(--bg3)', color: 'var(--text2)', fontWeight: 700,
              fontSize: 13, cursor: 'pointer', fontFamily: 'inherit',
            }}
          >
            Cancel
          </button>
          {bankMode ? (
            <button
              type="button"
              onClick={handleSaveToBank}
              disabled={savingBank}
              className="student-db-header__deploy-btn"
              style={{ opacity: savingBank ? 0.6 : 1 }}
            >
              {savingBank ? 'Saving...' : canEditBankProject ? 'Save to Bank' : 'Save a Copy'}
            </button>
          ) : (
            <button
              type="button"
              onClick={handleSave}
              disabled={saving}
              className="student-db-header__deploy-btn"
              style={{ opacity: saving ? 0.6 : 1 }}
            >
              {saving ? 'Saving...' : 'Save'}
            </button>
          )}
        </div>
      </header>

      {error && (
        <div className="editor-message editor-message--error">
          {error}
        </div>
      )}
      {successMsg && (
        <div className="editor-message editor-message--success">
          {successMsg}
        </div>
      )}

      <div className="teacher-editor-tabs">
        <button
          type="button"
          onClick={() => setActiveTab("theory")}
          className={"teacher-editor-tab" + (activeTab === "theory" ? " active" : "")}
        >
          Theory ({theoryCards.length} cards)
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("quiz")}
          className={"teacher-editor-tab" + (activeTab === "quiz" ? " active" : "")}
        >
          Quiz ({quizQuestions.length} questions)
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("rewards")}
          className={"teacher-editor-tab" + (activeTab === "rewards" ? " active" : "")}
        >
          Rewards ({rewardComponents.length} components)
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("assessment")}
          className={"teacher-editor-tab" + (activeTab === "assessment" ? " active" : "")}
        >
          Assessment
        </button>
      </div>

      <div className="teacher-editor-content">
        <div className="editor-pane">
          {activeTab === "theory" && (
            <div className="editor-tab-content">
              <div className="editor-toolbar">
                <div className="editor-toolbar-group">
                  <label>Filter</label>
                  <select
                    value={theoryDifficultyFilter}
                    onChange={(e) => setTheoryDifficultyFilter(e.target.value)}
                    className="editor-field"
                  >
                    <option value="all">All difficulties</option>
                    {DIFFICULTY_OPTIONS.map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="editor-toolbar-group">
                  <label>Sort</label>
                  <select
                    value={theoryDifficultySort}
                    onChange={(e) => setTheoryDifficultySort(e.target.value)}
                    className="editor-field"
                  >
                    <option value="original">Original order</option>
                    <option value="difficulty-asc">Easy to hard</option>
                    <option value="difficulty-desc">Hard to easy</option>
                  </select>
                </div>
              </div>
              {visibleTheoryCards.map(({ item: card, index: idx }, displayIdx) => (
                <div key={card.id} className="editor-card">
                  <div className="editor-card-header">
                    <strong>Card {displayIdx + 1}</strong>
                    <select
                      value={normalizeDifficulty(card.difficulty)}
                      onChange={(e) => updateCard(idx, "difficulty", normalizeDifficulty(e.target.value))}
                      className="editor-field editor-card-difficulty"
                      aria-label={`Difficulty for card ${displayIdx + 1}`}
                    >
                      {DIFFICULTY_OPTIONS.map((option) => (
                        <option key={option.value} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                    <button type="button" onClick={() => removeCard(idx)} className="btn-remove" title="Remove card">
                      Remove
                    </button>
                  </div>

                  <div className="editor-form-grid">
                    <label>Emoji</label>
                    <input
                      type="text"
                      value={card.emoji || ""}
                      onChange={(e) => updateCard(idx, "emoji", e.target.value)}
                      className="editor-field"
                    />

                    <label>Front</label>
                    <input
                      type="text"
                      value={card.front || ""}
                      onChange={(e) => updateCard(idx, "front", e.target.value)}
                      className="editor-field"
                      placeholder="Question/title"
                    />

                    <label>Simple</label>
                    <textarea
                      value={card.simple || ""}
                      onChange={(e) => updateCard(idx, "simple", e.target.value)}
                      rows={2}
                      className="editor-textarea"
                      placeholder="Short summary (back face)"
                    />

                    <label>Detail</label>
                    <textarea
                      value={card.detail || ""}
                      onChange={(e) => updateCard(idx, "detail", e.target.value)}
                      rows={4}
                      className="editor-textarea"
                      placeholder="Full explanation (back face)"
                    />

                    <label>Fun Fact</label>
                    <textarea
                      value={card.funFact || ""}
                      onChange={(e) => updateCard(idx, "funFact", e.target.value)}
                      rows={2}
                      className="editor-textarea"
                      placeholder="Optional fun fact"
                    />
                  </div>
                </div>
              ))}
              <button type="button" onClick={addCard} className="btn-add">
                + Add Card
              </button>
            </div>
          )}

          {activeTab === "quiz" && (
            <div className="editor-tab-content">
              <div className="editor-toolbar">
                <div className="editor-toolbar-group">
                  <label>Filter</label>
                  <select
                    value={quizDifficultyFilter}
                    onChange={(e) => setQuizDifficultyFilter(e.target.value)}
                    className="editor-field"
                  >
                    <option value="all">All difficulties</option>
                    {DIFFICULTY_OPTIONS.map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="editor-toolbar-group">
                  <label>Sort</label>
                  <select
                    value={quizDifficultySort}
                    onChange={(e) => setQuizDifficultySort(e.target.value)}
                    className="editor-field"
                  >
                    <option value="original">Original order</option>
                    <option value="difficulty-asc">Easy to hard</option>
                    <option value="difficulty-desc">Hard to easy</option>
                  </select>
                </div>
              </div>
              {visibleQuizQuestions.map(({ item: q, index: idx }, displayIdx) => (
                <div key={q.id || idx} className="editor-card">
                  <div className="editor-card-header">
                    <strong>Question {displayIdx + 1}</strong>
                    <select
                      value={normalizeDifficulty(q.difficulty)}
                      onChange={(e) => updateQuizQuestion(idx, "difficulty", normalizeDifficulty(e.target.value))}
                      className="editor-field editor-card-difficulty"
                      aria-label={`Difficulty for question ${displayIdx + 1}`}
                    >
                      {DIFFICULTY_OPTIONS.map((option) => (
                        <option key={option.value} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                    <button type="button" onClick={() => removeQuizQuestion(idx)} className="btn-remove" title="Remove question">
                      Remove
                    </button>
                  </div>

                  <div className="editor-form-grid">
                    <label>Question</label>
                    <input
                      type="text"
                      value={q.question || ""}
                      onChange={(e) => updateQuizQuestion(idx, "question", e.target.value)}
                      className="editor-field"
                      placeholder="Quiz question"
                    />

                    {[0, 1, 2, 3].map((optIdx) => (
                      <div key={optIdx} style={{ display: "contents" }}>
                        <label>Option {["A", "B", "C", "D"][optIdx]}</label>
                        <input
                          type="text"
                          value={q.options?.[optIdx] || ""}
                          onChange={(e) => updateQuizOption(idx, optIdx, e.target.value)}
                          className="editor-field"
                          placeholder={`Option ${["A", "B", "C", "D"][optIdx]}`}
                        />
                      </div>
                    ))}

                    <label>Correct Answer</label>
                    <select
                      value={q.correctAnswer || 0}
                      onChange={(e) => updateQuizQuestion(idx, "correctAnswer", Number(e.target.value))}
                      className="editor-field"
                    >
                      <option value={0}>A</option>
                      <option value={1}>B</option>
                      <option value={2}>C</option>
                      <option value={3}>D</option>
                    </select>
                  </div>
                </div>
              ))}
              <button type="button" onClick={addQuizQuestion} className="btn-add">
                + Add Question
              </button>
            </div>
          )}

          {activeTab === "rewards" && (
            <div className="editor-tab-content">
              <p className="editor-card-label" style={{ fontSize: 14, textAlign: "center", marginBottom: 12 }}>
                Select components students will unlock after completing this project:
              </p>
              <div style={{ display: "grid", gap: 10, marginBottom: 16 }}>
                <input
                  type="search"
                  value={rewardSearchQuery}
                  onChange={(e) => setRewardSearchQuery(e.target.value)}
                  className="editor-field"
                  placeholder="Search components..."
                  style={{ width: "100%", minWidth: 220 }}
                />
                <div style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }}>
                  {rewardCategories.map((category) => (
                    <button
                      key={category}
                      type="button"
                      onClick={() => setRewardCategoryFilter(category)}
                      className={"btn-filter" + (rewardCategoryFilter === category ? " active" : "")}
                      style={{
                        padding: "8px 12px",
                        borderRadius: 999,
                        border: rewardCategoryFilter === category ? "1px solid #60a5fa" : "1px solid rgba(148,163,184,.3)",
                        background: rewardCategoryFilter === category ? "rgba(96,165,250,.12)" : "rgba(255,255,255,.04)",
                        color: rewardCategoryFilter === category ? "#3b82f6" : "#cbd5e1",
                        cursor: "pointer",
                        fontSize: 12,
                        fontWeight: 700,
                      }}
                    >
                      {category}
                    </button>
                  ))}
                </div>
              </div>
              {filteredRewardComponents.length === 0 && (
                <div style={{ color: "#94a3b8", fontSize: 13, padding: "14px 12px", border: "1px dashed rgba(148,163,184,.4)", borderRadius: 10, textAlign: "center" }}>
                  No components match your search or selected category.
                </div>
              )}
              {filteredRewardComponents.map((comp) => {
                const isSelected = rewardComponents.includes(comp.id);
                return (
                  <div
                    key={comp.id}
                    onClick={() => toggleComponent(comp.id)}
                    className="editor-reward-card"
                    style={{
                      border: `1px solid ${isSelected ? comp.color + "60" : "rgba(255,255,255,.08)"}`,
                      background: isSelected ? comp.color + "12" : "rgba(255,255,255,.03)",
                    }}
                  >
                    <div
                      className="editor-reward-card__checkbox"
                      style={{
                        border: `2px solid ${isSelected ? comp.color : "rgba(255,255,255,.2)"}`,
                        background: isSelected ? comp.color : "transparent",
                        color: isSelected ? "#fff" : "transparent",
                      }}
                    >
                      {isSelected ? "✓" : ""}
                    </div>
                    <span style={{ fontSize: 24 }}>{comp.icon}</span>
                    <div className="editor-reward-card__info">
                      <div className="editor-reward-card__name">{comp.name}</div>
                      <div className="editor-reward-card__desc">{comp.category} • {comp.description?.slice(0, 60)}...</div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {activeTab === "assessment" && (
            <div style={{ display: "grid", gap: 14, justifyContent: "center" }}>
              <p className="assessment-upload-label" style={{ fontWeight: 700, textAlign: "center" }}>
                Upload a reference circuit PNG to auto-generate evaluation criteria.
                The image is never stored — only the extracted metadata is saved.
              </p>

              <label className="assessment-upload-label">Reference Circuit Image</label>

              <input
                ref={refCircuitInputRef}
                type="file"
                accept="image/png"
                onChange={handleRefCircuitUpload}
                style={{ display: "none" }}
              />

              {assessmentNodeContent.refCircuitName ? (
                <div className="assessment-file-box">
                  <span style={{ fontSize: 18 }}>📷</span>
                  <span style={{ flex: 1, fontSize: 13, color: "#e2e8f0", fontWeight: 600 }}>
                    {assessmentNodeContent.refCircuitName}
                  </span>
                  <span className="assessment-file-badge">
                    ✓ Criteria extracted
                  </span>
                  <button type="button" onClick={handleClearRefCircuit} className="btn-remove">
                    Remove
                  </button>
                </div>
              ) : (
                <button type="button" onClick={() => refCircuitInputRef.current?.click()} className="assessment-upload-box">
                  <span style={{ fontSize: 22 }}>📤</span>
                  Choose a PNG exported from OpenHW-Studio …
                </button>
              )}

              {assessmentNodeContent.autoGeneratedStatus === "error" && (
                <div className="assessment-error-box">
                  ⚠ {assessmentNodeContent.autoGeneratedError}
                </div>
              )}

              <div style={{ display: "flex", gap: 10, marginTop: 10, flexWrap: "wrap" }}>
                <button
                  type="button"
                  onClick={() => {
                    // Set flag to prevent state reset when we return from simulator
                    importedFromSimulatorRef.current = true;

                    // Store circuit meta (components/connections) for simulator to load
                    // If refCircuitFile exists, extract the meta and store it
                    if (assessmentNodeContent.refCircuitFile) {
                      try {
                        const meta = extractProjectMetaFromPng(assessmentNodeContent.refCircuitFile);
                        const payload = {
                          board: "arduino_uno",
                          code: "",
                          components: (meta.components || []).map((c) => ({
                            id: c.id,
                            type: c.type,
                            name: c.name,
                            x: c.x,
                            y: c.y,
                            rotation: c.rotation,
                          })),
                          connections: (meta.connections || []).map((w) => ({
                            from: w.from,
                            to: w.to,
                          })),
                        };
                        localStorage.setItem(SIMULATOR_CRITERIA_STORAGE_KEY, JSON.stringify(payload));
                      } catch (e) {
                        console.error("Failed to extract circuit meta for simulator:", e);
                        // Fallback: clear any stale data
                        localStorage.removeItem(SIMULATOR_CRITERIA_STORAGE_KEY);
                      }
                    } else {
                      // No PNG uploaded - clear any stale data and open empty simulator
                      localStorage.removeItem(SIMULATOR_CRITERIA_STORAGE_KEY);
                    }
                    const returnParams = new URLSearchParams(location.search);
                    returnParams.set("simulatorCriteria", "1");
                    const returnSearch = returnParams.toString();
                    const returnTo = `${location.pathname}${returnSearch ? `?${returnSearch}` : ""}`;
                    navigate(`/simulator?returnTo=${encodeURIComponent(returnTo)}`);
                  }}
                  style={{
                    padding: "10px 14px",
                    borderRadius: 10,
                    border: "1px solid var(--border)",
                    background: "var(--card2)",
                    color: "var(--text)",
                    fontWeight: 700,
                    cursor: "pointer",
                    fontSize: 13,
                  }}
                >
                  🧪 Create with Simulator
                </button>
              </div>

              {/* ── Auto-generated criteria preview ── */}
              {assessmentNodeContent.evaluationCriteria && Object.keys(assessmentNodeContent.evaluationCriteria).length > 0 && (
                <>
                  <label style={{ color: "#94a3b8", fontSize: 12, fontWeight: 700, marginTop: 8 }}>
                    Auto-generated Evaluation Criteria
                    <small style={{ fontWeight: 400, opacity: .7, marginLeft: 6 }}>
                      (read-only · derived from reference PNG)
                    </small>
                  </label>

                  {assessmentNodeContent.evaluationCriteria.components && (
                    <div style={{
                      border: "1px solid rgba(255,255,255,.07)", borderRadius: 10,
                      padding: 14, background: "rgba(255,255,255,.02)"
                    }}>
                      <div style={{
                        fontSize: 11, fontWeight: 800, color: "#94a3b8",
                        textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8
                      }}>
                        Components
                      </div>
                      {(assessmentNodeContent.evaluationCriteria.components.required || []).map((c, i) => (
                        <div key={i} style={{ fontSize: 12, color: "#cbd5e1" }}>
                          {c.count}× {c.type}
                        </div>
                      ))}
                    </div>
                  )}

                  {assessmentNodeContent.evaluationCriteria.wiringAccuracy && (
                    <div style={{
                      border: "1px solid rgba(255,255,255,.07)", borderRadius: 10,
                      padding: 14, background: "rgba(255,255,255,.02)"
                    }}>
                      <div style={{
                        fontSize: 11, fontWeight: 800, color: "#94a3b8",
                        textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8
                      }}>
                        Wiring
                      </div>
                      <div style={{ fontSize: 11, color: "#64748b" }}>
                        {(assessmentNodeContent.evaluationCriteria.wiringAccuracy.requiredConnections || []).length} connection checks
                      </div>
                    </div>
                  )}

                  {assessmentNodeContent.evaluationCriteria.codeFunctionality && (
                    <div style={{
                      border: "1px solid rgba(255,255,255,.07)", borderRadius: 10,
                      padding: 14, background: "rgba(255,255,255,.02)"
                    }}>
                      <div style={{
                        fontSize: 11, fontWeight: 800, color: "#94a3b8",
                        textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8
                      }}>
                        Code Functionality
                      </div>
                      <div style={{ fontSize: 11, color: "#64748b" }}>
                        Detected functions: {(
                          assessmentNodeContent.evaluationCriteria.codeFunctionality.requiredFunctions || []
                        ).join(", ") || "none"}
                        {assessmentNodeContent.evaluationCriteria.codeFunctionality.expectedBehavior?.pinNumber != null &&
                          <span> · pin {assessmentNodeContent.evaluationCriteria.codeFunctionality.expectedBehavior.pinNumber} {assessmentNodeContent.evaluationCriteria.codeFunctionality.expectedBehavior.pinMode}</span>
                        }
                        {assessmentNodeContent.evaluationCriteria.codeFunctionality.expectedBehavior?.blinkDelay != null &&
                          <span> · delay {assessmentNodeContent.evaluationCriteria.codeFunctionality.expectedBehavior.blinkDelay} ms</span>
                        }
                      </div>
                    </div>
                  )}
                </>
              )}

              {/* No criteria yet */}
              {(!assessmentNodeContent.evaluationCriteria || Object.keys(assessmentNodeContent.evaluationCriteria).length === 0) && (
                <div style={{
                  color: "#475569", fontSize: 12,
                  padding: "10px 12px", border: "1px dashed rgba(255,255,255,.07)",
                  borderRadius: 8, textAlign: "center"
                }}>
                  Upload a reference PNG to automatically generate components, wiring,
                  and code evaluation criteria.
                </div>
              )}

              {/* ── Passing Threshold ── */}
              <label style={{ color: "#94a3b8", fontSize: 12, fontWeight: 700, marginTop: 4 }}>
                Passing Threshold (%)
              </label>
              <input
                type="number"
                min={0}
                max={100}
                value={assessmentNodeContent.passingThreshold ?? 60}
                onChange={(e) => updateAssessmentField("passingThreshold", Number(e.target.value))}
                style={{
                  width: 80, background: "rgba(255,255,255,.05)",
                  border: "1px solid rgba(255,255,255,.1)", borderRadius: 6,
                  padding: "7px 10px", color: "#e2e8f0", fontSize: 13
                }}
              />

              {/* ── Manual scoring override (commented out) ── */}
              {/* <label style={{ color: "#94a3b8", fontSize: 12, fontWeight: 700 }}>
                 Scoring Tiers Override
                 <small style={{ fontWeight: 400, opacity: .7, marginLeft: 6 }}>
                   (optional JSON — customises feedback tiers)
                 </small>
               </label>
               <textarea
                 value={assessmentNodeContent.overrideJson || ""}
                 onChange={(e) => updateAssessmentField("overrideJson", e.target.value)}
                 rows={6}
                 spellCheck={false}
                 style={{
                   background: "rgba(0,0,0,.25)", border: "1px solid rgba(255,255,255,.1)",
                   borderRadius: 6, padding: "9px 11px", color: "#a5f3fc",
                   fontFamily: "'JetBrains Mono','Fira Code',monospace",
                   fontSize: 11, lineHeight: 1.6, resize: "vertical",
                 }}
                 placeholder='{ "feedbackTiers": { "excellent": { ... } }, "passingThreshold": 85 }'
               /> */}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
