import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { COMPONENTS } from "../../../services/gamification/ComponentsConfig";
import { getProjectFlashcards } from "../../../services/gamification/ProjectData";
import { PROJECTS } from "../../../services/gamification/ProjectsConfig";
import { buildFallbackClassAdventureContent, normalizeAdventureContent } from "../../../services/classAdventureAdapter";
import {
  getAdminGlobalAdventureConfig,
  updateAdminGlobalAdventureConfig,
} from "../../../services/classAdventureService";
import { extractProjectMetaFromPng } from "../../../utils/projectCompilerUtils";

const emptyAssessment = () => ({
  passingThreshold: 60,
  refCircuitFile: null,
  refCircuitName: "",
  evaluationCriteria: null,
  autoGeneratedStatus: null,
  autoGeneratedError: "",
  overrideJson: "",
});

const buildProjectDraft = (projectSlug) => {
  const template = getProjectFlashcards(projectSlug);
  return {
    theory: template.map((card, idx) => ({
      id: `card-${Date.now()}-${idx}`,
      emoji: card.emoji || "ðŸ“š",
      front: card.front || "",
      simple: card.simple || "",
      detail: card.detail || "",
      funFact: card.funFact || "",
    })),
    quizQuestions: template.map((card, idx) => ({
      id: `quiz-${Date.now()}-${idx}`,
      question: card.quiz?.question || card.front || "",
      options: card.quiz?.options?.slice(0, 4) || ["", "", "", ""],
      correctAnswer: Number.isFinite(card.quiz?.correctAnswer) ? card.quiz.correctAnswer : 0,
      explanation: card.detail || "",
    })),
    rewardComponents: [],
    assessment: emptyAssessment(),
  };
};

const buildNewProject = (worldId, index, projectMeta = null) => ({
  id: `project-${index}-${Date.now()}`,
  slug: `custom-project-${index}`,
  worldId,
  order: index,
  enabled: true,
  title: projectMeta?.title || `Custom Project ${index}`,
  subtitle: projectMeta?.subtitle || "",
  description: projectMeta?.description || "",
  prerequisite: projectMeta?.prerequisite || null,
  xpReward: projectMeta?.xpReward || 100,
  rewardComponents: [],
  theory: [],
  quizQuestions: [],
  nodes: [
    { id: "read", type: "theory", title: "Reading", order: 1, content: {} },
    { id: "quiz", type: "quiz", title: "Quiz", order: 2, content: {} },
    { id: "unlock", type: "reward", title: "Component Unlock", order: 3, content: {} },
    { id: "sim", type: "assessment", title: "Project Assessment", order: 4, content: {} },
  ],
  assessment: {
    passingThreshold: 60,
    evaluationCriteria: null,
    scoring: {},
  },
});

export default function AdminAdventureContentTab() {
  const [content, setContent] = useState(null);
  const [selectedSlug, setSelectedSlug] = useState(PROJECTS[0]?.slug || "");
  const [theoryCards, setTheoryCards] = useState([]);
  const [quizQuestions, setQuizQuestions] = useState([]);
  const [rewardComponents, setRewardComponents] = useState([]);
  const [assessmentNodeContent, setAssessmentNodeContent] = useState(emptyAssessment());
  const [activeTab, setActiveTab] = useState("theory");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [successMsg, setSuccessMsg] = useState("");
  const [editingWorldId, setEditingWorldId] = useState(null);
  const [editingProjectId, setEditingProjectId] = useState(null);
  const refCircuitInputRef = useRef(null);

  const selectedProjectMeta = useMemo(
    () => PROJECTS.find((project) => project.slug === selectedSlug),
    [selectedSlug],
  );
  const resolvedContent = useMemo(() => normalizeAdventureContent(content), [content]);
  const activeProject = useMemo(
    () => (resolvedContent.projects || []).find((project) => project.slug === selectedSlug) || null,
    [resolvedContent, selectedSlug],
  );
  const worldGroups = useMemo(() => {
    const worldRows = Array.isArray(resolvedContent.worlds) && resolvedContent.worlds.length
      ? resolvedContent.worlds.slice().sort((a, b) => (a.order || 0) - (b.order || 0))
      : [];
    const projectRows = Array.isArray(resolvedContent.projects) ? resolvedContent.projects : [];

    if (worldRows.length > 0) {
      return worldRows.map((world, worldIndex) => ({
        ...world,
        title: world.title || `World ${worldIndex + 1}`,
        color: world.color || "#3b82f6",
        icon: world.icon || "ðŸ§­",
        projects: projectRows
          .filter((project) => project.worldId === world.id)
          .sort((a, b) => (a.order || 0) - (b.order || 0)),
      }));
    }

    const map = new Map();
    projectRows.forEach((project, index) => {
      const worldId = project.worldId || `world-${PROJECTS.find((p) => p.slug === project.slug)?.world || 1}`;
      if (!map.has(worldId)) {
        map.set(worldId, {
          id: worldId,
          title: `World ${String(worldId).replace("world-", "") || 1}`,
          theme: "",
          color: PROJECTS.find((p) => p.slug === project.slug)?.color || "#3b82f6",
          icon: "ðŸ§­",
          order: Number(String(worldId).replace("world-", "")) || index + 1,
          projects: [],
        });
      }
      map.get(worldId).projects.push(project);
    });

    return [...map.values()]
      .map((world) => ({
        ...world,
        projects: world.projects.slice().sort((a, b) => (a.order || 0) - (b.order || 0)),
      }))
      .sort((a, b) => (a.order || 0) - (b.order || 0));
  }, [resolvedContent]);

  useEffect(() => {
    try {
      localStorage.removeItem("openhw_adventure_content");
      localStorage.removeItem("openhw_global_adventure_content");
    } catch {
      // ignore localStorage cleanup failures
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      setLoading(true);
      setError("");
      try {
        const response = await getAdminGlobalAdventureConfig();
        if (cancelled) return;
        const serverContent = response?.config || buildFallbackClassAdventureContent();
        setContent(normalizeAdventureContent(serverContent));
      } catch (loadError) {
        if (!cancelled) {
          setError(loadError?.message || "Failed to load global adventure content");
          setContent(buildFallbackClassAdventureContent());
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!selectedSlug) return;

    const fallbackProject = buildFallbackClassAdventureContent().projects.find(
      (project) => project.slug === selectedSlug,
    );
    const sourceProject = activeProject || fallbackProject || null;
    const sourceFlashcards = sourceProject?.theory?.length ? sourceProject.theory : getProjectFlashcards(selectedSlug);

    setTheoryCards(
      (sourceFlashcards || []).map((card, idx) => ({
        id: card.id || `card-${selectedSlug || "project"}-${idx}`,
        emoji: card.emoji || "",
        front: card.front || "",
        simple: card.simple || "",
        detail: card.detail || "",
        funFact: card.funFact || "",
      })),
    );

    const sourceQuestions = sourceProject?.quizQuestions?.length
      ? sourceProject.quizQuestions
      : (getProjectFlashcards(selectedSlug) || []).map((card, idx) => ({
          id: card.id || `quiz-${selectedSlug || "project"}-${idx}`,
          question: card.quiz?.question || card.front || "",
          options: card.quiz?.options?.slice(0, 4) || ["", "", "", ""],
          correctAnswer: Number.isFinite(card.quiz?.correctAnswer) ? Number(card.quiz.correctAnswer) : 0,
          explanation: card.detail || "",
        }));

    setQuizQuestions(
      (sourceQuestions || []).map((question, idx) => ({
        id: question.id || `quiz-${selectedSlug || "project"}-${idx}`,
        question: question.question || "",
        options: (question.options || ["", "", "", ""]).slice(0, 4),
        correctAnswer: Number.isFinite(question.correctAnswer) ? Number(question.correctAnswer) : 0,
        explanation: question.explanation || "",
      })),
    );

    setRewardComponents(
      (sourceProject?.rewardComponents?.length ? sourceProject.rewardComponents : fallbackProject?.rewardComponents || [])
        .map((component) => component.id || component.type || component.slug || component)
        .filter(Boolean),
    );

    const assessmentSource = sourceProject?.assessment || sourceProject?.evaluation || fallbackProject?.assessment || fallbackProject?.evaluation || {};
    setAssessmentNodeContent({
      ...emptyAssessment(),
      ...assessmentSource,
      passingThreshold: Number.isFinite(assessmentSource?.passingThreshold) ? Number(assessmentSource.passingThreshold) : 60,
      evaluationCriteria: assessmentSource?.evaluationCriteria ?? null,
      overrideJson: assessmentSource?.scoring ? JSON.stringify(assessmentSource.scoring, null, 2) : "",
    });
  }, [selectedSlug, activeProject]);

  const updateAssessmentField = (field, value) => {
    setAssessmentNodeContent((prev) => ({ ...prev, [field]: value }));
  };

  const updateWorld = (worldId, field, value) => {
    setContent((prev) => ({
      ...(prev || buildFallbackClassAdventureContent()),
      worlds: (prev?.worlds || []).map((world) => (world.id === worldId ? { ...world, [field]: value } : world)),
    }));
  };

  const updateProject = (projectId, field, value) => {
    setContent((prev) => ({
      ...(prev || buildFallbackClassAdventureContent()),
      projects: (prev?.projects || []).map((project) => (project.id === projectId ? { ...project, [field]: value } : project)),
    }));
  };

  const addWorld = () => {
    setContent((prev) => {
      const current = prev || buildFallbackClassAdventureContent();
      const worlds = [...(current.worlds || [])];
      const nextOrder = worlds.length + 1;
      return {
        ...current,
        worlds: [
          ...worlds,
          {
            id: `world-${nextOrder}-${Date.now()}`,
            title: `World ${nextOrder}`,
            theme: "",
            color: "#3b82f6",
            icon: "??",
            order: nextOrder,
          },
        ],
      };
    });
  };

  const moveWorld = (worldId, delta) => {
    setContent((prev) => {
      const current = prev || buildFallbackClassAdventureContent();
      const worlds = [...(current.worlds || [])].sort((a, b) => (a.order || 0) - (b.order || 0));
      const index = worlds.findIndex((world) => world.id === worldId);
      const nextIndex = index + delta;
      if (index < 0 || nextIndex < 0 || nextIndex >= worlds.length) return current;
      [worlds[index], worlds[nextIndex]] = [worlds[nextIndex], worlds[index]];
      return { ...current, worlds: worlds.map((world, idx) => ({ ...world, order: idx + 1 })) };
    });
  };

  const deleteWorld = (worldId) => {
    if (!window.confirm("Delete this world and its projects?")) return;
    setContent((prev) => {
      const current = prev || buildFallbackClassAdventureContent();
      return {
        ...current,
        worlds: (current.worlds || []).filter((world) => world.id !== worldId),
        projects: (current.projects || []).filter((project) => project.worldId !== worldId),
      };
    });
  };

  const addProject = (worldId) => {
    setContent((prev) => {
      const current = prev || buildFallbackClassAdventureContent();
      const projects = [...(current.projects || [])];
      const nextIndex = projects.length + 1;
      return {
        ...current,
        projects: [...projects, buildNewProject(worldId, nextIndex, PROJECTS[nextIndex - 1] || null)],
      };
    });
  };

  const moveProject = (projectId, delta) => {
    setContent((prev) => {
      const current = prev || buildFallbackClassAdventureContent();
      const projects = [...(current.projects || [])];
      const index = projects.findIndex((project) => project.id === projectId);
      const nextIndex = index + delta;
      if (index < 0 || nextIndex < 0 || nextIndex >= projects.length) return current;
      [projects[index], projects[nextIndex]] = [projects[nextIndex], projects[index]];
      return { ...current, projects: projects.map((project, idx) => ({ ...project, order: idx + 1 })) };
    });
  };

  const deleteProject = (projectId) => {
    if (!window.confirm("Delete this project and all its content?")) return;
    const projectToDelete = (content?.projects || []).find((project) => project.id === projectId);
    setContent((prev) => {
      const current = prev || buildFallbackClassAdventureContent();
      return {
        ...current,
        projects: (current.projects || []).filter((project) => project.id !== projectId),
      };
    });
    if (projectToDelete?.slug === selectedSlug) {
      setSelectedSlug(PROJECTS[0]?.slug || "");
    }
  };

  const updateTheoryCard = (index, field, value) => {
    setTheoryCards((prev) => prev.map((card, idx) => (idx === index ? { ...card, [field]: value } : card)));
  };

  const addTheoryCard = () => {
    setTheoryCards((prev) => [
      ...prev,
      { id: `card-${Date.now()}`, emoji: "??", front: "", simple: "", detail: "", funFact: "" },
    ]);
  };

  const removeTheoryCard = (index) => {
    setTheoryCards((prev) => prev.filter((_, idx) => idx !== index));
  };

  const updateQuizQuestion = (index, field, value) => {
    setQuizQuestions((prev) => prev.map((question, idx) => (idx === index ? { ...question, [field]: value } : question)));
  };

  const updateQuizOption = (index, optionIndex, value) => {
    setQuizQuestions((prev) => prev.map((question, idx) => (
      idx === index
        ? { ...question, options: (question.options || ["", "", "", ""]).map((option, innerIdx) => innerIdx === optionIndex ? value : option) }
        : question
    )));
  };

  const addQuizQuestion = () => {
    setQuizQuestions((prev) => [
      ...prev,
      { id: `quiz-${Date.now()}`, question: "", options: ["", "", "", ""], correctAnswer: 0, explanation: "" },
    ]);
  };

  const removeQuizQuestion = (index) => {
    setQuizQuestions((prev) => prev.filter((_, idx) => idx !== index));
  };

  const handleRefCircuitUpload = useCallback(async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;
    try {
      const arrayBuffer = await file.arrayBuffer();
      const meta = extractProjectMetaFromPng(arrayBuffer);
      const evaluationCriteria = {
        components: { required: (meta.components || []).map((c) => ({ type: c.type || "unknown", count: 1 })), weight: 0.25 },
        wiringAccuracy: { requiredConnections: meta.connections || [], weight: 0.35 },
        codeFunctionality: { requiredFunctions: [], expectedBehavior: {}, weight: 0.4 },
      };
      setAssessmentNodeContent((prev) => ({
        ...prev,
        refCircuitFile: arrayBuffer,
        refCircuitName: file.name,
        evaluationCriteria,
        autoGeneratedStatus: "ok",
        autoGeneratedError: "",
      }));
    } catch (uploadError) {
      setAssessmentNodeContent((prev) => ({
        ...prev,
        refCircuitFile: null,
        refCircuitName: "",
        evaluationCriteria: null,
        autoGeneratedStatus: "error",
        autoGeneratedError: uploadError.message || "Failed to read PNG metadata",
      }));
    }
  }, []);

  const handleSaveAdventureConfig = async () => {
    setSaving(true);
    setError("");
    setSuccessMsg("");
    try {
      const currentContent = content || buildFallbackClassAdventureContent();
      const projects = [...(currentContent.projects || [])];
      const idx = projects.findIndex((project) => project.slug === selectedSlug);
      const existingProject = idx >= 0 ? projects[idx] : null;
      const baseProject = selectedProjectMeta || PROJECTS.find((project) => project.slug === selectedSlug) || { slug: selectedSlug, title: selectedSlug };
      let scoring = {};
      if (assessmentNodeContent.overrideJson?.trim()) {
        scoring = JSON.parse(assessmentNodeContent.overrideJson);
      }
      const rewardComponentPayload = rewardComponents.map((compId) => {
        const component = COMPONENTS.find((c) => c.id === compId);
        return component
          ? {
              id: component.id,
              name: component.name,
              icon: component.icon,
              color: component.color,
              desc: component.description || "",
              description: component.description || "",
            }
          : { id: compId };
      });
      const payload = {
        ...(existingProject || {}),
        id: existingProject?.id || `global-${selectedSlug}`,
        slug: selectedSlug,
        worldId: existingProject?.worldId || `world-${baseProject.world || 1}`,
        order: Number.isFinite(existingProject?.order) ? existingProject.order : (baseProject.number || projects.length + 1),
        enabled: true,
        title: existingProject?.title || baseProject.title || selectedSlug,
        subtitle: existingProject?.subtitle || baseProject.subtitle || "",
        description: existingProject?.description || baseProject.description || "",
        prerequisite: existingProject?.prerequisite ?? baseProject.prerequisite ?? null,
        xpReward: existingProject?.xpReward ?? baseProject.xpReward ?? 0,
        theory: theoryCards,
        quizQuestions,
        rewardComponents: rewardComponentPayload,
        assessment: {
          passingThreshold: Number(assessmentNodeContent.passingThreshold ?? 60),
          evaluationCriteria: assessmentNodeContent.evaluationCriteria || {},
          scoring,
        },
      };
      if (idx >= 0) {
        projects[idx] = payload;
      } else {
        projects.push(payload);
      }

      const nextContent = { ...currentContent, projects };
      const response = await updateAdminGlobalAdventureConfig(nextContent);
      setContent(response?.config || nextContent);
      setSuccessMsg("Adventure config saved.");
    } catch (saveError) {
      if (saveError instanceof SyntaxError) {
        setError("Assessment JSON is invalid.");
      } else {
        setError(saveError?.message || "Failed to save adventure config");
      }
    } finally {
      setSaving(false);
    }
  };
  return (
    <div className="ad-adventure-wrap space-y-8 pb-8">
      <div className="rounded-[28px] border border-white/10 bg-slate-950/70 p-8 md:p-10 shadow-2xl shadow-black/25">
        <div className="flex flex-wrap items-start gap-5">
          <div className="min-w-0">
            <div className="text-[11px] font-black uppercase tracking-[0.32em] text-cyan-300">
              Adventure Dashboard
            </div>
            <h3 className="mt-3 text-3xl font-black text-slate-50">
              Global adventure content
            </h3>
            <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">
              Admins can reshape the adventure structure here. Worlds can be reordered and edited,
              projects can be moved between worlds, and the selected project opens a dedicated editor
              on the right.
            </p>
          </div>
          <div className="ml-auto flex flex-wrap gap-3">
            <button
              type="button"
              onClick={addWorld}
              className="rounded-xl border border-cyan-400/30 bg-cyan-500/10 px-5 py-3 text-sm font-black uppercase tracking-widest text-cyan-100"
            >
              + Add World
            </button>
            <button
              type="button"
              onClick={() => window.open("/adventure", "_blank", "noopener,noreferrer")}
              className="rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-black uppercase tracking-widest text-slate-200"
            >
              Preview Map
            </button>
            <button
              type="button"
              onClick={handleSaveAdventureConfig}
              disabled={saving}
              className="rounded-xl bg-cyan-600 px-5 py-3 text-sm font-black uppercase tracking-widest text-white disabled:opacity-60"
            >
              {saving ? "Saving..." : "Save Adventure"}
            </button>
          </div>
        </div>
        {error ? (
          <div className="mt-5 rounded-2xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-sm font-bold text-rose-200">
            {error}
          </div>
        ) : null}
        {successMsg ? (
          <div className="mt-5 rounded-2xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm font-bold text-emerald-200">
            {successMsg}
          </div>
        ) : null}
      </div>

      <div className="grid gap-10 xl:grid-cols-[1.08fr_0.92fr]">
        <section className="space-y-5">
          <div className="rounded-[28px] border border-white/10 bg-slate-950/65 p-7 md:p-8">
            <div className="flex flex-wrap items-center gap-4">
              <div>
                <div className="text-[11px] font-black uppercase tracking-[0.32em] text-slate-500">
                  Worlds
                </div>
                <div className="mt-2 text-sm text-slate-400">
                  {worldGroups.length} world groups in the global adventure
                </div>
              </div>
              <div className="ml-auto rounded-2xl border border-white/10 bg-white/5 px-4 py-2 text-xs font-bold text-slate-400">
                Selected: {selectedProjectMeta?.title || selectedSlug}
              </div>
            </div>
          </div>

          <div className="space-y-6">
            {worldGroups.map((world, worldIndex) => {
              const worldProjects = world.projects || [];
              const projectCount = worldProjects.length;

              return (
                <article
                  key={world.id}
                  className="rounded-3xl border border-white/10 bg-slate-950/60 p-6 md:p-7 shadow-lg shadow-black/10"
                >
                  <div className="flex flex-wrap items-start gap-6">
                    <div
                      className="flex h-14 w-14 items-center justify-center rounded-2xl border border-white/10 text-2xl"
                      style={{ background: `${world.color}18`, color: world.color }}
                    >
                      {world.icon}
                    </div>

                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="rounded-full border border-cyan-400/20 bg-cyan-500/10 px-2.5 py-1 text-[10px] font-black uppercase tracking-widest text-cyan-200">
                          World {worldIndex + 1}
                        </span>
                        <span className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">
                          {projectCount} projects
                        </span>
                      </div>

                      <div className="mt-5 grid gap-5 md:grid-cols-[1.35fr_1fr_0.7fr]">
                        <div className="grid gap-2">
                          {editingWorldId === world.id ? (
                            <input
                              autoFocus
                              type="text"
                              value={world.title || ""}
                              onChange={(event) => updateWorld(world.id, "title", event.target.value)}
                              onBlur={() => setEditingWorldId(null)}
                              onKeyDown={(event) => {
                                if (event.key === "Enter") {
                                  event.currentTarget.blur();
                                }
                                if (event.key === "Escape") {
                                  event.currentTarget.blur();
                                }
                              }}
                              className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-xl font-black text-slate-50 outline-none transition focus:border-cyan-400/40 focus:ring-2 focus:ring-cyan-500/10"
                              placeholder={`World ${worldIndex + 1}`}
                              onClick={(event) => event.stopPropagation()}
                            />
                          ) : (
                            <button
                              type="button"
                              onClick={(event) => {
                                event.stopPropagation();
                                setEditingWorldId(world.id);
                              }}
                              className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-left text-xl font-black text-slate-50 transition hover:border-cyan-400/30 hover:bg-cyan-500/10"
                            >
                              {world.title || `World ${worldIndex + 1}`}
                            </button>
                          )}
                        </div>

                        <label className="grid gap-2">
                          <span className="text-[11px] font-black uppercase tracking-[0.24em] text-slate-500">
                            Theme
                          </span>
                          <input
                            type="text"
                            value={world.theme || ""}
                            onChange={(event) => updateWorld(world.id, "theme", event.target.value)}
                            className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-sm font-semibold text-slate-100 outline-none transition focus:border-cyan-400/40 focus:ring-2 focus:ring-cyan-500/10"
                            placeholder="Desert, Space, Forest..."
                            onClick={(event) => event.stopPropagation()}
                          />
                        </label>

                        <label className="grid gap-2">
                          <span className="text-[11px] font-black uppercase tracking-[0.24em] text-slate-500">
                            Color
                          </span>
                          <input
                            type="color"
                            value={world.color || "#3b82f6"}
                            onChange={(event) => updateWorld(world.id, "color", event.target.value)}
                            className="h-[56px] rounded-2xl border border-white/10 bg-slate-950 p-2"
                            onClick={(event) => event.stopPropagation()}
                          />
                        </label>
                      </div>
                    </div>

                    <div className="flex flex-wrap gap-2 xl:justify-end">
                      <button
                        type="button"
                        onClick={() => moveWorld(world.id, -1)}
                        disabled={worldIndex === 0}
                        className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-black uppercase tracking-widest text-slate-200 disabled:cursor-not-allowed disabled:opacity-40"
                      >
                        Up
                      </button>
                      <button
                        type="button"
                        onClick={() => moveWorld(world.id, 1)}
                        disabled={worldIndex === worldGroups.length - 1}
                        className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-black uppercase tracking-widest text-slate-200 disabled:cursor-not-allowed disabled:opacity-40"
                      >
                        Down
                      </button>
                      <button
                        type="button"
                        onClick={() => addProject(world.id)}
                        className="rounded-xl border border-cyan-400/20 bg-cyan-500/10 px-4 py-3 text-sm font-black uppercase tracking-widest text-cyan-100"
                      >
                        + Project
                      </button>
                      <button
                        type="button"
                        onClick={() => deleteWorld(world.id)}
                        className="rounded-xl border border-rose-400/20 bg-rose-500/10 px-4 py-3 text-sm font-black uppercase tracking-widest text-rose-100"
                      >
                        Delete
                      </button>
                    </div>
                  </div>

                  <div className="mt-7 space-y-4">
                    {worldProjects.map((project, projectIndex) => {
                      const isActive = project.slug === selectedSlug;
                      const base = PROJECTS.find((item) => item.slug === project.slug);
                      const accent = base?.color || world.color || "#3b82f6";

                      return (
                        <article
                          key={project.id}
                          onClick={() => setSelectedSlug(project.slug)}
                          className={`rounded-2xl border p-4 md:p-5 transition cursor-pointer ${
                            isActive
                              ? "border-cyan-400/35 bg-cyan-500/10 shadow-[0_0_0_1px_rgba(34,211,238,0.12)]"
                              : "border-white/10 bg-white/[0.04] hover:border-cyan-400/25 hover:bg-cyan-500/[0.05]"
                          }`}
                        >
                          <div className="flex flex-col gap-5">
                            <div
                              className="flex h-12 w-12 items-center justify-center rounded-2xl text-lg font-black"
                              style={{ background: `${accent}18`, color: accent }}
                            >
                              {base?.icon || "??"}
                            </div>

                            <div className="min-w-0 flex-1">
                              {editingProjectId === project.id ? (
                                <input
                                  autoFocus
                                  type="text"
                                  value={project.title || ""}
                                  onChange={(event) => updateProject(project.id, "title", event.target.value)}
                                  onBlur={() => setEditingProjectId(null)}
                                  onKeyDown={(event) => {
                                    if (event.key === "Enter" || event.key === "Escape") {
                                      event.currentTarget.blur();
                                    }
                                  }}
                                  onClick={(event) => event.stopPropagation()}
                                  className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-2xl font-black text-slate-50 outline-none transition focus:border-cyan-400/40 focus:ring-2 focus:ring-cyan-500/10"
                                  placeholder={project.slug}
                                />
                              ) : (
                                <button
                                  type="button"
                                  onClick={(event) => {
                                    event.stopPropagation();
                                    setEditingProjectId(project.id);
                                  }}
                                  className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-left text-2xl font-black text-slate-50 transition hover:border-cyan-400/30 hover:bg-cyan-500/10"
                                >
                                  {project.title || project.slug}
                                </button>
                              )}

                              <p className="mt-4 text-sm leading-6 text-slate-400">
                                {project.theory?.length || 0} theory cards · {project.quizQuestions?.length || 0} quiz questions · {project.rewardComponents?.length || 0} rewards
                              </p>
                            </div>

                            <div className="flex flex-wrap gap-2">
                              <button
                                type="button"
                                onClick={() => moveProject(project.id, -1)}
                                disabled={projectIndex === 0}
                                className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-black uppercase tracking-widest text-slate-200 disabled:cursor-not-allowed disabled:opacity-40"
                              >
                                Up
                              </button>
                              <button
                                type="button"
                                onClick={() => moveProject(project.id, 1)}
                                disabled={projectIndex === worldProjects.length - 1}
                                className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-black uppercase tracking-widest text-slate-200 disabled:cursor-not-allowed disabled:opacity-40"
                              >
                                Down
                              </button>
                              <button
                                type="button"
                                onClick={() => deleteProject(project.id)}
                                className="rounded-xl border border-rose-400/20 bg-rose-500/10 px-4 py-3 text-sm font-black uppercase tracking-widest text-rose-100"
                              >
                                Delete
                              </button>
                            </div>
                          </div>

                          <div className="mt-6 grid gap-5 md:grid-cols-[0.55fr_auto]">
                            <label className="grid gap-2 max-w-xs">
                              <span className="text-[11px] font-black uppercase tracking-[0.24em] text-slate-500">
                                XP reward
                              </span>
                              <input
                                type="number"
                                min="0"
                                value={project.xpReward || 0}
                                onChange={(event) => updateProject(project.id, "xpReward", Number(event.target.value || 0))}
                                onClick={(event) => event.stopPropagation()}
                                className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-sm font-semibold text-slate-100 outline-none transition focus:border-cyan-400/40 focus:ring-2 focus:ring-cyan-500/10"
                              />
                            </label>
                          </div>
                        </article>
                      );
                    })}

                    {worldProjects.length === 0 ? (
                      <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.03] px-5 py-6 text-sm text-slate-400">
                        No projects yet. Use <span className="font-bold text-slate-200">+ Project</span> to add one to this world.
                      </div>
                    ) : null}
                  </div>
                </article>
              );
            })}
          </div>
        </section>

        <section className="space-y-6 rounded-[28px] border border-white/10 bg-slate-950/65 p-7 md:p-8 shadow-lg shadow-black/10 xl:sticky xl:top-6">
          <div className="flex flex-wrap items-start gap-4">
            <div className="min-w-0">
              <div className="text-[11px] font-black uppercase tracking-[0.32em] text-slate-500">
                Project Editor
              </div>
              <div className="mt-2 text-3xl font-black leading-tight text-slate-50">
                {selectedProjectMeta?.title || activeProject?.title || selectedSlug}
              </div>
              <p className="mt-3 text-sm leading-6 text-slate-400">
                This editor updates the selected project’s theory, quiz, rewards, and assessment data.
              </p>
            </div>
            <div className="ml-auto flex flex-wrap items-center gap-2">
              <span className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-[11px] font-black uppercase tracking-widest text-slate-300">
                {selectedSlug}
              </span>
              <button
                type="button"
                onClick={() => setSelectedSlug(PROJECTS[0]?.slug || selectedSlug)}
                className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-black uppercase tracking-widest text-slate-200"
              >
                Reset
              </button>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 pt-1 pb-1">
            {['theory', 'quiz', 'rewards', 'assessment'].map((tab) => (
              <button
                key={tab}
                type="button"
                onClick={() => setActiveTab(tab)}
                className={`rounded-xl px-3 py-2 text-xs font-black uppercase tracking-widest transition ${
                  activeTab === tab ? 'bg-cyan-600 text-white' : 'bg-white/5 text-slate-300'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>

          <div className="space-y-6">
            {activeTab === 'theory' ? (
              <div className="space-y-6">
                {theoryCards.map((card, index) => (
                  <div key={card.id || index} className="rounded-2xl border border-white/10 bg-white/5 p-5 space-y-4">
                    <div className="flex flex-wrap items-center gap-3">
                      <input
                        value={card.emoji || ''}
                        onChange={(e) => updateTheoryCard(index, 'emoji', e.target.value)}
                        className="w-24 rounded-xl border border-white/10 bg-slate-950 px-3 py-3 text-sm text-slate-100"
                        placeholder="Emoji"
                      />
                      <input
                        value={card.front || ''}
                        onChange={(e) => updateTheoryCard(index, 'front', e.target.value)}
                        className="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                        placeholder={`Card ${index + 1} title`}
                      />
                      <button
                        type="button"
                        onClick={() => removeTheoryCard(index)}
                        className="rounded-xl border border-rose-400/20 bg-rose-500/10 px-4 py-2.5 text-xs font-black text-rose-200"
                      >
                        Remove
                      </button>
                    </div>
                    <textarea
                      value={card.simple || ''}
                      onChange={(e) => updateTheoryCard(index, 'simple', e.target.value)}
                      className="h-28 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                      placeholder="Simple explanation"
                    />
                    <textarea
                      value={card.detail || ''}
                      onChange={(e) => updateTheoryCard(index, 'detail', e.target.value)}
                      className="h-36 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                      placeholder="Detailed explanation"
                    />
                    <textarea
                      value={card.funFact || ''}
                      onChange={(e) => updateTheoryCard(index, 'funFact', e.target.value)}
                      className="h-24 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                      placeholder="Fun fact"
                    />
                  </div>
                ))}
                <button
                  type="button"
                  onClick={addTheoryCard}
                  className="rounded-xl border border-dashed border-white/15 bg-white/5 px-4 py-3 text-xs font-black uppercase tracking-widest text-slate-100"
                >
                  Add Card
                </button>
              </div>
            ) : null}

            {activeTab === 'quiz' ? (
              <div className="space-y-6">
                {quizQuestions.map((question, index) => (
                  <div key={question.id || index} className="rounded-2xl border border-white/10 bg-white/5 p-5 space-y-4">
                    <div className="flex flex-wrap items-center gap-3">
                      <input
                        value={question.question || ''}
                        onChange={(e) => updateQuizQuestion(index, 'question', e.target.value)}
                        className="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                        placeholder={`Question ${index + 1}`}
                      />
                      <select
                        value={question.correctAnswer || 0}
                        onChange={(e) => updateQuizQuestion(index, 'correctAnswer', Number(e.target.value))}
                        className="rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                      >
                        <option value={0}>A</option>
                        <option value={1}>B</option>
                        <option value={2}>C</option>
                        <option value={3}>D</option>
                      </select>
                      <button
                        type="button"
                        onClick={() => removeQuizQuestion(index)}
                        className="rounded-xl border border-rose-400/20 bg-rose-500/10 px-4 py-2.5 text-xs font-black text-rose-200"
                      >
                        Remove
                      </button>
                    </div>
                    <div className="grid gap-3 md:grid-cols-2">
                      {(question.options || ['', '', '', '']).map((option, optionIndex) => (
                        <input
                          key={optionIndex}
                          value={option || ''}
                          onChange={(e) => updateQuizOption(index, optionIndex, e.target.value)}
                          className="rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                          placeholder={`Option ${['A', 'B', 'C', 'D'][optionIndex]}`}
                        />
                      ))}
                    </div>
                    <textarea
                      value={question.explanation || ''}
                      onChange={(e) => updateQuizQuestion(index, 'explanation', e.target.value)}
                      className="h-28 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-100"
                      placeholder="Explanation"
                    />
                  </div>
                ))}
                <button
                  type="button"
                  onClick={addQuizQuestion}
                  className="rounded-xl border border-dashed border-white/15 bg-white/5 px-4 py-3 text-xs font-black uppercase tracking-widest text-slate-100"
                >
                  Add Question
                </button>
              </div>
            ) : null}

            {activeTab === 'rewards' ? (
              <div className="grid gap-3 md:grid-cols-2">
                {COMPONENTS.map((component) => {
                  const selected = rewardComponents.includes(component.id);
                  return (
                    <button
                      key={component.id}
                      type="button"
                      onClick={() => setRewardComponents((prev) => (
                        selected ? prev.filter((id) => id !== component.id) : [...prev, component.id]
                      ))}
                      className={`rounded-2xl border p-4 text-left transition ${
                        selected
                          ? 'border-cyan-400/40 bg-cyan-500/10'
                          : 'border-white/10 bg-white/5 hover:border-cyan-400/30'
                      }`}
                    >
                      <div className="text-sm font-black text-slate-100">{component.name}</div>
                      <div className="mt-1 text-xs text-slate-400">{component.category}</div>
                    </button>
                  );
                })}
              </div>
            ) : null}

            {activeTab === 'assessment' ? (
              <div className="space-y-6">
                <input
                  ref={refCircuitInputRef}
                  type="file"
                  accept="image/png"
                  onChange={handleRefCircuitUpload}
                  className="hidden"
                />
                <div className="flex flex-wrap gap-3">
                  <button
                    type="button"
                    onClick={() => refCircuitInputRef.current?.click()}
                    className="rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-black uppercase tracking-widest text-slate-200"
                  >
                    Upload Reference PNG
                  </button>
                  <input
                    type="number"
                    min={0}
                    max={100}
                    value={assessmentNodeContent.passingThreshold ?? 60}
                    onChange={(e) => updateAssessmentField('passingThreshold', Number(e.target.value))}
                    className="w-32 rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-slate-100"
                  />
                </div>
                {assessmentNodeContent.refCircuitName ? (
                  <div className="text-xs font-bold text-emerald-300">
                    {assessmentNodeContent.refCircuitName}
                  </div>
                ) : null}
                {assessmentNodeContent.autoGeneratedError ? (
                  <div className="text-xs font-bold text-rose-300">
                    {assessmentNodeContent.autoGeneratedError}
                  </div>
                ) : null}
                <textarea
                  value={JSON.stringify(assessmentNodeContent.evaluationCriteria || {}, null, 2)}
                  readOnly
                  className="h-40 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 font-mono text-xs text-sky-100"
                />
                <textarea
                  value={assessmentNodeContent.overrideJson || ''}
                  onChange={(e) => updateAssessmentField('overrideJson', e.target.value)}
                  className="h-40 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100"
                  placeholder='{"components":{"excellent":{"min":90,"feedback":"..."}}}'
                />
              </div>
            ) : null}
          </div>
        </section>
      </div>
    </div>
  );
}
